import { initializePresentation } from './presentation.mjs';
import { initializeGlossEntries } from './gloss-entries.mjs';
import { initializeGrammarPopup } from './grammar-popup.mjs';
import { initializeDocumentShell } from './document-shell.mjs';
import { initializeAnnotations } from './annotations.mjs';
import { initializeHoverLayout } from './hover-layout.mjs';
import { initializeLookupProgress } from './lookup-progress.mjs';
import { initializeDocumentState } from './document-state.mjs';
import { initializeFoliateViewport } from './foliate-viewport.mjs';
import { initializeFoliateSlices } from './foliate-slices.mjs';
import { initializeDocumentNavigation } from './document-navigation.mjs';
import { initializeContinuousScroll } from './continuous-scroll.mjs';
import { initializeViewportClamping } from './viewport-clamping.mjs';
import { initializeDependencyState } from './dependency-state.mjs';
import { initializeMwtContext } from './mwt-context.mjs';
import { initializeTokenFragments } from './token-fragments.mjs';
import { initializeDependencyGeometry } from './dependency-geometry.mjs';
import { initializeDependencyHover } from './dependency-hover.mjs';
import { initializeDependencyPopup } from './dependency-popup.mjs';
import { initializeGlossRequests } from './gloss-requests.mjs';
import { initializeDecompositionRequests } from './decomposition-requests.mjs';
import { initializeOrthography } from './orthography.mjs';
import { initializeSettingsPanels } from './settings-panels.mjs';
import { initializeEntryForms } from './entry-forms.mjs';
import { initializeDocumentImport } from './document-import.mjs';
import { initializeFillSlices } from './fill-slices.mjs';
import { initializeSegmentRendering } from './segment-rendering.mjs';
import { initializeHoverInteraction } from './hover-interaction.mjs';
import { initializeDictionaryPopup } from './dictionary-popup.mjs';
import { initializeSidePanel } from './side-panel.mjs';
import { initializeDecompositionEditor } from './decomposition-editor.mjs';
import { initializeTokenBannerMenu } from './token-banner-menu.mjs';
import { initializeTokenMap } from './token-map.mjs';
import { initializeFlashcards } from './flashcards.mjs';

/** Initialize features in the original script order. */
function bootstrap() {
  if (!initializePresentation()) return;
  if (!initializeGlossEntries()) return;
  if (!initializeGrammarPopup()) return;
  if (!initializeDocumentShell()) return;
  if (!initializeAnnotations()) return;
  if (!initializeHoverLayout()) return;
  if (!initializeLookupProgress()) return;
  if (!initializeDocumentState()) return;
  if (!initializeFoliateViewport()) return;
  if (!initializeFoliateSlices()) return;
  if (!initializeDocumentNavigation()) return;
  if (!initializeContinuousScroll()) return;
  if (!initializeViewportClamping()) return;
  if (!initializeDependencyState()) return;
  if (!initializeMwtContext()) return;
  if (!initializeTokenFragments()) return;
  if (!initializeDependencyGeometry()) return;
  if (!initializeDependencyHover()) return;
  if (!initializeDependencyPopup()) return;
  if (!initializeGlossRequests()) return;
  if (!initializeDecompositionRequests()) return;
  if (!initializeOrthography()) return;
  if (!initializeSettingsPanels()) return;
  if (!initializeEntryForms()) return;
  if (!initializeDocumentImport()) return;
  if (!initializeFillSlices()) return;
  if (!initializeSegmentRendering()) return;
  if (!initializeHoverInteraction()) return;
  if (!initializeDictionaryPopup()) return;
  if (!initializeSidePanel()) return;
  if (!initializeDecompositionEditor()) return;
  if (!initializeTokenBannerMenu()) return;
  if (!initializeTokenMap()) return;
  if (!initializeFlashcards()) return;
}
bootstrap();
