#!/usr/bin/env python3
"""Export Ancient Greek LSJ headword paradigms generated by greek-inflexion.

This script:
- reads unique LSJ headwords from dict_sqlite/grc-lsj.rebuilt.sqlite
- keeps only headwords whose source rows are noun/adj/verb
- uses the greek-inflexion verb or nominal stemming rules, depending on POS
- synthesizes a tiny in-memory lexicon from the headword's own possible stems
- streams every generated form plus detail metadata to a TSV file

The exported TSV is intended for inspection, not for serving the app runtime.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sqlite3
import sys
from collections import OrderedDict, defaultdict
from pathlib import Path
from typing import Iterable, Iterator

import yaml


ROOT = Path(__file__).resolve().parents[2]
VENDORED_INFLEXION_ROOT = ROOT / "tmp_inflexion_master" / "inflexion-master"
VENDORED_GREEK_ACCENT_ROOT = ROOT / "tmp_greek_accentuation_master" / "greek-accentuation-master"
VENDORED_GREEK_INFLEXION_ROOT = ROOT / "tmp_greek_inflexion_master" / "greek-inflexion-master"

for _path in (
    VENDORED_INFLEXION_ROOT,
    VENDORED_GREEK_ACCENT_ROOT,
    VENDORED_GREEK_INFLEXION_ROOT,
):
    sys.path.insert(0, str(_path))

from accent import calculate_accent, debreath, rebreath, strip_accents  # noqa: E402
from greek_accentuation.characters import strip_length as do_strip_length  # noqa: E402
from inflexion import Inflexion  # noqa: E402
from inflexion.lexicon import Lexicon  # noqa: E402
from inflexion.stemming import StemmingRuleSet  # noqa: E402


DB_PATH = ROOT / "dict_sqlite" / "grc-lsj.rebuilt.sqlite"
VERB_STEMMING_PATH = VENDORED_GREEK_INFLEXION_ROOT / "stemming.yaml"
NOMINAL_STEMMING_PATH = VENDORED_GREEK_INFLEXION_ROOT / "noun_stemming.yaml"
DEFAULT_OUTPUT_PATH = ROOT / "reports" / "grc_lsj_greek_inflexion_paradigms.tsv"

NOMINAL_KEY_RE = re.compile(r"^[NGDAV][SP][MFN]$")


def load_stemming_utf8(stemming_file: Path, strip_length: bool = False) -> StemmingRuleSet:
    """Load a stemming rule file using UTF-8 explicitly."""
    ruleset = StemmingRuleSet()

    with open(stemming_file, encoding="utf-8") as f:
        stemming_dict = yaml.safe_load(f)

    for key, rules in stemming_dict.items():
        while isinstance(rules, dict) and "ref" in rules:
            if rules["ref"] in stemming_dict:
                rules = stemming_dict[rules["ref"]]
            else:
                raise KeyError(f"ref to {rules['ref']} which does not exist")

        for rule in rules:
            if strip_length:
                rule = do_strip_length(rule)
            if ";" in rule:
                rule, annotation = rule.split(";", 1)
                ruleset.add(key, rule, {annotation})
            else:
                ruleset.add(key, rule)

    return ruleset


class EngineContext:
    """Minimal greek-inflexion runtime with explicit UTF-8 loading."""

    def __init__(self, stemming_path: Path):
        self.ruleset = load_stemming_utf8(stemming_path)
        self.inflexion = Inflexion()
        self.lexicon = Lexicon()
        self.inflexion.add_lexicon(self.lexicon)
        self.inflexion.add_stemming_rule_set(self.ruleset)
        self.form_override = {}
        self.accent_override = defaultdict(list)
        self.segmented_lemmas = {}

    def possible_stems(self, form: str):
        for key, stem in self.ruleset.possible_stems(debreath(form)):
            if stem != "h":
                yield key, rebreath(strip_accents(stem))

    def possible_stems2(self, form: str):
        for key, stem in self.ruleset.possible_stems2(debreath(form)):
            yield key, rebreath(strip_accents(stem))

    def generate(self, lemma: str, key: str, tags=None):
        overrides = self.form_override.get((lemma, key))
        if overrides:
            if isinstance(overrides, str):
                overrides = [overrides]
            return {override: [{"override": "form"}] for override in overrides}

        generated = defaultdict(list)
        for orig_form, details in self.inflexion.generate(lemma, key, tags or set()).items():
            for detail in details:
                detail = dict(detail)
                segmented_lemma = self.segmented_lemmas.get(lemma)
                accent_result = None
                try:
                    accent_result = calculate_accent(
                        orig_form,
                        key,
                        lemma,
                        segmented_lemma,
                        detail["stem"],
                        self.inflexion,
                        self.accent_override,
                    )
                except Exception as exc:
                    accent_result = (orig_form, f"accent fallback: {type(exc).__name__}")

                if accent_result is None:
                    accent_form, accent_notes = orig_form, "accent unavailable"
                else:
                    accent_form, accent_notes = accent_result

                detail["original_form"] = orig_form
                detail["accent_notes"] = accent_notes
                generated[accent_form].append(detail)
        return generated


def family_from_candidate_key(key: str, bucket: str) -> str | None:
    """Map a candidate parse key to the family regex we should generate."""
    if bucket == "nominal":
        if NOMINAL_KEY_RE.fullmatch(key):
            return f"..{key[-1]}"
        return None

    if "." in key:
        return key.split(".", 1)[0]
    if len(key) == 3:
        return key
    return None


def json_compact(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def iter_grouped_rows(conn: sqlite3.Connection) -> Iterator[tuple[str, list[sqlite3.Row]]]:
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    rows = cur.execute(
        """
        SELECT id, headword, headword_key, lemma, pos, commentary, etymology_number
        FROM entries
        WHERE pos IN ('noun', 'adj', 'verb')
          AND headword IS NOT NULL
          AND trim(headword) != ''
        ORDER BY headword, id
        """
    )

    current_headword = None
    current_group: list[sqlite3.Row] = []
    for row in rows:
        headword = row["headword"]
        if current_headword is None:
            current_headword = headword
        if headword != current_headword:
            yield current_headword, current_group
            current_headword = headword
            current_group = [row]
        else:
            current_group.append(row)

    if current_headword is not None:
        yield current_headword, current_group


def unique_preserve(values: Iterable[str]) -> list[str]:
    seen = OrderedDict()
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if not text:
            continue
        seen.setdefault(text, None)
    return list(seen.keys())


def format_source_meta(rows: list[sqlite3.Row]) -> dict[str, str]:
    return {
        "source_ids": ",".join(str(row["id"]) for row in rows),
        "source_pos_values": ",".join(unique_preserve(row["pos"] for row in rows)),
        "source_lemma_values": ",".join(unique_preserve(row["lemma"] for row in rows)),
        "source_headword_key_values": ",".join(
            unique_preserve(row["headword_key"] for row in rows)
        ),
        "source_etymology_numbers": ",".join(
            unique_preserve(
                "" if row["etymology_number"] is None else str(row["etymology_number"])
                for row in rows
            )
        ),
        "source_row_count": str(len(rows)),
    }


def collect_family_candidates(engine: EngineContext, headword: str, bucket: str):
    families: OrderedDict[str, dict] = OrderedDict()
    candidate_sources = (
        ("possible_stems", engine.possible_stems),
        ("possible_stems2", engine.possible_stems2),
    )

    for source_name, func in candidate_sources:
        try:
            candidates = list(func(headword))
        except Exception:
            continue

        for key, stem in candidates:
            family = family_from_candidate_key(key, bucket)
            if not family:
                continue
            if stem == "0":
                continue

            family_info = families.setdefault(
                family,
                {
                    "stems": OrderedDict(),
                    "candidates": OrderedDict(),
                },
            )

            family_info["stems"].setdefault(stem, None)
            cand_key = (key, stem)
            candidate = family_info["candidates"].setdefault(
                cand_key,
                {"key": key, "stem": stem, "sources": []},
            )
            if source_name not in candidate["sources"]:
                candidate["sources"].append(source_name)

    return families


def build_family_lexicon(headword: str, families: dict[str, dict]) -> Lexicon:
    lexicon = Lexicon()
    for family, info in families.items():
        for stem in info["stems"].keys():
            lexicon.add(headword, family, stem)
    return lexicon


def matching_rule_keys(
    engine: EngineContext, family: str, cache: dict[str, list[str]]
) -> list[str]:
    if family in cache:
        return cache[family]
    keys = [key for key in sorted(engine.ruleset.key_to_rules) if re.match(family, key)]
    cache[family] = keys
    return keys


def serialize_detail(detail: dict) -> dict:
    stemming = detail.get("stemming", {}) or {}
    rule = stemming.get("rule")
    normalized = dict(detail)
    normalized["stemming"] = dict(stemming)
    if rule is not None:
        normalized["stemming"]["rule"] = repr(rule)
    return normalized


def write_rows_for_headword(
    writer: csv.writer,
    engine_name: str,
    engine: EngineContext,
    headword: str,
    bucket_rows: list[sqlite3.Row],
    bucket: str,
    rule_key_cache: dict[str, list[str]],
) -> tuple[int, int]:
    families = collect_family_candidates(engine, headword, bucket)
    if not families:
        return 0, 0

    engine.lexicon = build_family_lexicon(headword, families)
    engine.inflexion.lexicons = [engine.lexicon]

    source_meta = format_source_meta(bucket_rows)
    rows_written = 0
    families_used = 0

    for family, info in families.items():
        rule_keys = matching_rule_keys(engine, family, rule_key_cache)
        if not rule_keys:
            continue

        family_candidates_json = json_compact(
            {
                "family": family,
                "candidates": list(info["candidates"].values()),
            }
        )
        seed_key = next(iter(info["candidates"].values()))["key"]
        families_used += 1

        for generated_key in rule_keys:
            try:
                generated = engine.generate(headword, generated_key)
            except Exception as exc:
                # Keep the export running. Record the failure in the TSV.
                writer.writerow(
                    [
                        headword,
                        engine_name,
                        source_meta["source_ids"],
                        source_meta["source_pos_values"],
                        source_meta["source_lemma_values"],
                        source_meta["source_headword_key_values"],
                        source_meta["source_etymology_numbers"],
                        source_meta["source_row_count"],
                        family,
                        seed_key,
                        family_candidates_json,
                        generated_key,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        json_compact({"error": f"{type(exc).__name__}: {exc}"}),
                    ]
                )
                rows_written += 1
                continue

            for form, details in generated.items():
                for detail in details:
                    normalized = serialize_detail(detail)
                    stemming = normalized.get("stemming", {}) or {}
                    row = [
                        headword,
                        engine_name,
                        source_meta["source_ids"],
                        source_meta["source_pos_values"],
                        source_meta["source_lemma_values"],
                        source_meta["source_headword_key_values"],
                        source_meta["source_etymology_numbers"],
                        source_meta["source_row_count"],
                        family,
                        seed_key,
                        family_candidates_json,
                        generated_key,
                        form,
                        normalized.get("stem", ""),
                        normalized.get("original_form", ""),
                        normalized.get("accent_notes", ""),
                        stemming.get("base", ""),
                        stemming.get("ending", ""),
                        stemming.get("rule", ""),
                        str(stemming.get("used_default", "")),
                        json_compact(normalized),
                    ]
                    writer.writerow(row)
                    rows_written += 1

    return rows_written, families_used


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Export greek-inflexion paradigms for LSJ headwords to TSV"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path to the TSV output file",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Optional headword limit for smoke tests (0 = no limit)",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if not DB_PATH.exists():
        raise FileNotFoundError(f"Database not found: {DB_PATH}")
    if not VERB_STEMMING_PATH.exists():
        raise FileNotFoundError(f"Verb stemming file not found: {VERB_STEMMING_PATH}")
    if not NOMINAL_STEMMING_PATH.exists():
        raise FileNotFoundError(f"Nominal stemming file not found: {NOMINAL_STEMMING_PATH}")

    args.output.parent.mkdir(parents=True, exist_ok=True)

    verb_engine = EngineContext(VERB_STEMMING_PATH)
    nominal_engine = EngineContext(NOMINAL_STEMMING_PATH)
    verb_rule_key_cache: dict[str, list[str]] = {}
    nominal_rule_key_cache: dict[str, list[str]] = {}

    total_headwords = 0
    total_rows = 0
    total_families = 0
    skipped_no_candidates = 0
    processed_groups = 0

    with (
        sqlite3.connect(str(DB_PATH)) as conn,
        open(args.output, "w", encoding="utf-8", newline="") as out_file,
    ):
        writer = csv.writer(out_file, delimiter="\t")
        writer.writerow(
            [
                "headword",
                "engine_kind",
                "source_ids",
                "source_pos_values",
                "source_lemma_values",
                "source_headword_key_values",
                "source_etymology_numbers",
                "source_row_count",
                "family_regex",
                "family_seed_key",
                "family_candidates_json",
                "generated_key",
                "generated_form",
                "stem",
                "original_form",
                "accent_notes",
                "stemming_base",
                "stemming_ending",
                "stemming_rule",
                "stemming_used_default",
                "detail_json",
            ]
        )

        for headword, rows in iter_grouped_rows(conn):
            total_headwords += 1
            if args.limit and total_headwords > args.limit:
                break

            processed_groups += 1
            verb_rows = [row for row in rows if row["pos"] == "verb"]
            nominal_rows = [row for row in rows if row["pos"] in {"noun", "adj"}]

            if verb_rows:
                rows_written, families_used = write_rows_for_headword(
                    writer,
                    "verb",
                    verb_engine,
                    headword,
                    verb_rows,
                    "verb",
                    verb_rule_key_cache,
                )
                total_rows += rows_written
                total_families += families_used
                if families_used == 0:
                    skipped_no_candidates += 1

            if nominal_rows:
                rows_written, families_used = write_rows_for_headword(
                    writer,
                    "nominal",
                    nominal_engine,
                    headword,
                    nominal_rows,
                    "nominal",
                    nominal_rule_key_cache,
                )
                total_rows += rows_written
                total_families += families_used
                if families_used == 0:
                    skipped_no_candidates += 1

            if processed_groups % 500 == 0:
                print(
                    f"processed={processed_groups} rows={total_rows} families={total_families}",
                    file=sys.stderr,
                )

    print(
        (
            f"done headwords={processed_groups} rows={total_rows} "
            f"families={total_families} skipped_no_candidates={skipped_no_candidates} "
            f"output={args.output}"
        ),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
