import { ancientGreekState } from './ancient-greek.state.mjs';
import { registryState } from './registry.state.mjs';
export function initializeAncientGreek() {
  ancientGreekState.XPOS_GRC = {
    '---------': 'Empty / Unspecified Perseus Tag',
    '---pna---': 'Unspecified Part Of Speech, Present, Infinitive, Active',
    '--s---fa-': 'Unspecified Part Of Speech, Singular, Feminine, Accusative',
    '--s---ma-': 'Unspecified Part Of Speech, Singular, Masculine, Accusative',
    '--s---ng-': 'Unspecified Part Of Speech, Singular, Neuter, Genitive',
    '-2ppsa---': 'Unspecified Part Of Speech, Second Person, Plural, Present, Subjunctive, Active',
    '-2sasa---': 'Unspecified Part Of Speech, Second Person, Singular, Aorist, Subjunctive, Active',
    '-3paim---': 'Unspecified Part Of Speech, Third Person, Plural, Aorist, Indicative, Middle',
    '-3piia---': 'Unspecified Part Of Speech, Third Person, Plural, Imperfect, Indicative, Active',
    '-3siia---': 'Unspecified Part Of Speech, Third Person, Singular, Imperfect, Indicative, Active',
    'a--------': 'Adjective',
    'a-------s': 'Adjective, Superlative',
    'a-----na-': 'Adjective, Neuter, Accusative',
    'a-d----a-': 'Adjective, Dual, Accusative',
    'a-d---fd-': 'Adjective, Dual, Feminine, Dative',
    'a-d---fg-': 'Adjective, Dual, Feminine, Genitive',
    'a-d---fn-': 'Adjective, Dual, Feminine, Nominative',
    'a-d---fnc': 'Adjective, Dual, Feminine, Nominative, Comparative',
    'a-d---ma-': 'Adjective, Dual, Masculine, Accusative',
    'a-d---mg-': 'Adjective, Dual, Masculine, Genitive',
    'a-d---mn-': 'Adjective, Dual, Masculine, Nominative',
    'a-d---na-': 'Adjective, Dual, Neuter, Accusative',
    'a-d---ng-': 'Adjective, Dual, Neuter, Genitive',
    'a-d---nn-': 'Adjective, Dual, Neuter, Nominative',
    'a-p----dc': 'Adjective, Plural, Dative, Comparative',
    'a-p----gc': 'Adjective, Plural, Genitive, Comparative',
    'a-p---fa-': 'Adjective, Plural, Feminine, Accusative',
    'a-p---fac': 'Adjective, Plural, Feminine, Accusative, Comparative',
    'a-p---fas': 'Adjective, Plural, Feminine, Accusative, Superlative',
    'a-p---fd-': 'Adjective, Plural, Feminine, Dative',
    'a-p---fg-': 'Adjective, Plural, Feminine, Genitive',
    'a-p---fn-': 'Adjective, Plural, Feminine, Nominative',
    'a-p---fnc': 'Adjective, Plural, Feminine, Nominative, Comparative',
    'a-p---fns': 'Adjective, Plural, Feminine, Nominative, Superlative',
    'a-p---fv-': 'Adjective, Plural, Feminine, Vocative',
    'a-p---m--': 'Adjective, Plural, Masculine',
    'a-p---ma-': 'Adjective, Plural, Masculine, Accusative',
    'a-p---mac': 'Adjective, Plural, Masculine, Accusative, Comparative',
    'a-p---mas': 'Adjective, Plural, Masculine, Accusative, Superlative',
    'a-p---md-': 'Adjective, Plural, Masculine, Dative',
    'a-p---mdc': 'Adjective, Plural, Masculine, Dative, Comparative',
    'a-p---mds': 'Adjective, Plural, Masculine, Dative, Superlative',
    'a-p---mg-': 'Adjective, Plural, Masculine, Genitive',
    'a-p---mgc': 'Adjective, Plural, Masculine, Genitive, Comparative',
    'a-p---mgs': 'Adjective, Plural, Masculine, Genitive, Superlative',
    'a-p---mn-': 'Adjective, Plural, Masculine, Nominative',
    'a-p---mnc': 'Adjective, Plural, Masculine, Nominative, Comparative',
    'a-p---mns': 'Adjective, Plural, Masculine, Nominative, Superlative',
    'a-p---mv-': 'Adjective, Plural, Masculine, Vocative',
    'a-p---na-': 'Adjective, Plural, Neuter, Accusative',
    'a-p---nac': 'Adjective, Plural, Neuter, Accusative, Comparative',
    'a-p---nas': 'Adjective, Plural, Neuter, Accusative, Superlative',
    'a-p---nd-': 'Adjective, Plural, Neuter, Dative',
    'a-p---ndc': 'Adjective, Plural, Neuter, Dative, Comparative',
    'a-p---nds': 'Adjective, Plural, Neuter, Dative, Superlative',
    'a-p---ng-': 'Adjective, Plural, Neuter, Genitive',
    'a-p---ngc': 'Adjective, Plural, Neuter, Genitive, Comparative',
    'a-p---ngs': 'Adjective, Plural, Neuter, Genitive, Superlative',
    'a-p---nn-': 'Adjective, Plural, Neuter, Nominative',
    'a-p---nnc': 'Adjective, Plural, Neuter, Nominative, Comparative',
    'a-p---nns': 'Adjective, Plural, Neuter, Nominative, Superlative',
    'a-p---nv-': 'Adjective, Plural, Neuter, Vocative',
    'a-s----a-': 'Adjective, Singular, Accusative',
    'a-s----d-': 'Adjective, Singular, Dative',
    'a-s----dc': 'Adjective, Singular, Dative, Comparative',
    'a-s----g-': 'Adjective, Singular, Genitive',
    'a-s----gc': 'Adjective, Singular, Genitive, Comparative',
    'a-s---f--': 'Adjective, Singular, Feminine',
    'a-s---fa-': 'Adjective, Singular, Feminine, Accusative',
    'a-s---fac': 'Adjective, Singular, Feminine, Accusative, Comparative',
    'a-s---fas': 'Adjective, Singular, Feminine, Accusative, Superlative',
    'a-s---fd-': 'Adjective, Singular, Feminine, Dative',
    'a-s---fdc': 'Adjective, Singular, Feminine, Dative, Comparative',
    'a-s---fds': 'Adjective, Singular, Feminine, Dative, Superlative',
    'a-s---fg-': 'Adjective, Singular, Feminine, Genitive',
    'a-s---fgc': 'Adjective, Singular, Feminine, Genitive, Comparative',
    'a-s---fgs': 'Adjective, Singular, Feminine, Genitive, Superlative',
    'a-s---fn-': 'Adjective, Singular, Feminine, Nominative',
    'a-s---fnc': 'Adjective, Singular, Feminine, Nominative, Comparative',
    'a-s---fns': 'Adjective, Singular, Feminine, Nominative, Superlative',
    'a-s---fv-': 'Adjective, Singular, Feminine, Vocative',
    'a-s---m--': 'Adjective, Singular, Masculine',
    'a-s---ma-': 'Adjective, Singular, Masculine, Accusative',
    'a-s---mac': 'Adjective, Singular, Masculine, Accusative, Comparative',
    'a-s---mas': 'Adjective, Singular, Masculine, Accusative, Superlative',
    'a-s---md-': 'Adjective, Singular, Masculine, Dative',
    'a-s---mdc': 'Adjective, Singular, Masculine, Dative, Comparative',
    'a-s---mds': 'Adjective, Singular, Masculine, Dative, Superlative',
    'a-s---mg-': 'Adjective, Singular, Masculine, Genitive',
    'a-s---mgc': 'Adjective, Singular, Masculine, Genitive, Comparative',
    'a-s---mgs': 'Adjective, Singular, Masculine, Genitive, Superlative',
    'a-s---mn-': 'Adjective, Singular, Masculine, Nominative',
    'a-s---mnc': 'Adjective, Singular, Masculine, Nominative, Comparative',
    'a-s---mns': 'Adjective, Singular, Masculine, Nominative, Superlative',
    'a-s---mv-': 'Adjective, Singular, Masculine, Vocative',
    'a-s---mvs': 'Adjective, Singular, Masculine, Vocative, Superlative',
    'a-s---na-': 'Adjective, Singular, Neuter, Accusative',
    'a-s---nac': 'Adjective, Singular, Neuter, Accusative, Comparative',
    'a-s---nas': 'Adjective, Singular, Neuter, Accusative, Superlative',
    'a-s---nd-': 'Adjective, Singular, Neuter, Dative',
    'a-s---ndc': 'Adjective, Singular, Neuter, Dative, Comparative',
    'a-s---nds': 'Adjective, Singular, Neuter, Dative, Superlative',
    'a-s---ng-': 'Adjective, Singular, Neuter, Genitive',
    'a-s---ngc': 'Adjective, Singular, Neuter, Genitive, Comparative',
    'a-s---nn-': 'Adjective, Singular, Neuter, Nominative',
    'a-s---nnc': 'Adjective, Singular, Neuter, Nominative, Comparative',
    'a-s---nns': 'Adjective, Singular, Neuter, Nominative, Superlative',
    'a-s---nv-': 'Adjective, Singular, Neuter, Vocative',
    'a-s---nvs': 'Adjective, Singular, Neuter, Vocative, Superlative',
    'c--------': 'Conjunction',
    'd---': 'Adverb, Mood=?, Voice=?, Gender=?, Case=?, Degree=? (Truncated / Malformed Tag)',
    'd--------': 'Adverb',
    'd-------c': 'Adverb, Comparative',
    'd-------s': 'Adverb, Superlative',
    'g--------': 'Particle',
    'i--------': 'Interjection',
    'l--------': 'Article',
    'l-----fd-': 'Article, Feminine, Dative',
    'l-d---fa-': 'Article, Dual, Feminine, Accusative',
    'l-d---mn-': 'Article, Dual, Masculine, Nominative',
    'l-d---ng-': 'Article, Dual, Neuter, Genitive',
    'l-p---fa-': 'Article, Plural, Feminine, Accusative',
    'l-p---fd-': 'Article, Plural, Feminine, Dative',
    'l-p---fg-': 'Article, Plural, Feminine, Genitive',
    'l-p---fn-': 'Article, Plural, Feminine, Nominative',
    'l-p---ma-': 'Article, Plural, Masculine, Accusative',
    'l-p---md-': 'Article, Plural, Masculine, Dative',
    'l-p---mg-': 'Article, Plural, Masculine, Genitive',
    'l-p---mn-': 'Article, Plural, Masculine, Nominative',
    'l-p---na-': 'Article, Plural, Neuter, Accusative',
    'l-p---nd-': 'Article, Plural, Neuter, Dative',
    'l-p---ng-': 'Article, Plural, Neuter, Genitive',
    'l-p---nn-': 'Article, Plural, Neuter, Nominative',
    'l-s----d-': 'Article, Singular, Dative',
    'l-s---fa-': 'Article, Singular, Feminine, Accusative',
    'l-s---fd-': 'Article, Singular, Feminine, Dative',
    'l-s---fg-': 'Article, Singular, Feminine, Genitive',
    'l-s---fn-': 'Article, Singular, Feminine, Nominative',
    'l-s---m--': 'Article, Singular, Masculine',
    'l-s---ma-': 'Article, Singular, Masculine, Accusative',
    'l-s---md-': 'Article, Singular, Masculine, Dative',
    'l-s---mg-': 'Article, Singular, Masculine, Genitive',
    'l-s---mn-': 'Article, Singular, Masculine, Nominative',
    'l-s---na-': 'Article, Singular, Neuter, Accusative',
    'l-s---nd-': 'Article, Singular, Neuter, Dative',
    'l-s---ng-': 'Article, Singular, Neuter, Genitive',
    'l-s---nn-': 'Article, Singular, Neuter, Nominative',
    'l-s---nv-': 'Article, Singular, Neuter, Vocative',
    'm--------': 'Numeral',
    'm-p---md-': 'Numeral, Plural, Masculine, Dative',
    'm-s---ma-': 'Numeral, Singular, Masculine, Accusative',
    'm-s---mg-': 'Numeral, Singular, Masculine, Genitive',
    'm-s---mn-': 'Numeral, Singular, Masculine, Nominative',
    'm-s---na-': 'Numeral, Singular, Neuter, Accusative',
    'n--------': 'Noun',
    'n-----fg-': 'Noun, Feminine, Genitive',
    'n-----md-': 'Noun, Masculine, Dative',
    'n-----na-': 'Noun, Neuter, Accusative',
    'n-----nn-': 'Noun, Neuter, Nominative',
    'n-d---fa-': 'Noun, Dual, Feminine, Accusative',
    'n-d---fd-': 'Noun, Dual, Feminine, Dative',
    'n-d---fg-': 'Noun, Dual, Feminine, Genitive',
    'n-d---fn-': 'Noun, Dual, Feminine, Nominative',
    'n-d---ma-': 'Noun, Dual, Masculine, Accusative',
    'n-d---md-': 'Noun, Dual, Masculine, Dative',
    'n-d---mg-': 'Noun, Dual, Masculine, Genitive',
    'n-d---mn-': 'Noun, Dual, Masculine, Nominative',
    'n-d---mv-': 'Noun, Dual, Masculine, Vocative',
    'n-d---na-': 'Noun, Dual, Neuter, Accusative',
    'n-d---ng-': 'Noun, Dual, Neuter, Genitive',
    'n-d---nn-': 'Noun, Dual, Neuter, Nominative',
    'n-p----a-': 'Noun, Plural, Accusative',
    'n-p----d-': 'Noun, Plural, Dative',
    'n-p----g-': 'Noun, Plural, Genitive',
    'n-p---fa-': 'Noun, Plural, Feminine, Accusative',
    'n-p---fd-': 'Noun, Plural, Feminine, Dative',
    'n-p---fg-': 'Noun, Plural, Feminine, Genitive',
    'n-p---fn-': 'Noun, Plural, Feminine, Nominative',
    'n-p---fv-': 'Noun, Plural, Feminine, Vocative',
    'n-p---ma-': 'Noun, Plural, Masculine, Accusative',
    'n-p---md-': 'Noun, Plural, Masculine, Dative',
    'n-p---mg-': 'Noun, Plural, Masculine, Genitive',
    'n-p---mn-': 'Noun, Plural, Masculine, Nominative',
    'n-p---mv-': 'Noun, Plural, Masculine, Vocative',
    'n-p---na-': 'Noun, Plural, Neuter, Accusative',
    'n-p---nd-': 'Noun, Plural, Neuter, Dative',
    'n-p---ng-': 'Noun, Plural, Neuter, Genitive',
    'n-p---nn-': 'Noun, Plural, Neuter, Nominative',
    'n-p---nv-': 'Noun, Plural, Neuter, Vocative',
    'n-s----a-': 'Noun, Singular, Accusative',
    'n-s----d-': 'Noun, Singular, Dative',
    'n-s----g-': 'Noun, Singular, Genitive',
    'n-s----n-': 'Noun, Singular, Nominative',
    'n-s---fa-': 'Noun, Singular, Feminine, Accusative',
    'n-s---fd-': 'Noun, Singular, Feminine, Dative',
    'n-s---fg-': 'Noun, Singular, Feminine, Genitive',
    'n-s---fn-': 'Noun, Singular, Feminine, Nominative',
    'n-s---fv-': 'Noun, Singular, Feminine, Vocative',
    'n-s---ma-': 'Noun, Singular, Masculine, Accusative',
    'n-s---md-': 'Noun, Singular, Masculine, Dative',
    'n-s---mg-': 'Noun, Singular, Masculine, Genitive',
    'n-s---mn-': 'Noun, Singular, Masculine, Nominative',
    'n-s---mv-': 'Noun, Singular, Masculine, Vocative',
    'n-s---na-': 'Noun, Singular, Neuter, Accusative',
    'n-s---nd-': 'Noun, Singular, Neuter, Dative',
    'n-s---ng-': 'Noun, Singular, Neuter, Genitive',
    'n-s---nn-': 'Noun, Singular, Neuter, Nominative',
    'n-s---nv-': 'Noun, Singular, Neuter, Vocative',
    'p--------': 'Pronoun',
    'p-d----a-': 'Pronoun, Dual, Accusative',
    'p-d----d-': 'Pronoun, Dual, Dative',
    'p-d----g-': 'Pronoun, Dual, Genitive',
    'p-d----n-': 'Pronoun, Dual, Nominative',
    'p-d---fa-': 'Pronoun, Dual, Feminine, Accusative',
    'p-d---fd-': 'Pronoun, Dual, Feminine, Dative',
    'p-d---fn-': 'Pronoun, Dual, Feminine, Nominative',
    'p-d---ma-': 'Pronoun, Dual, Masculine, Accusative',
    'p-d---md-': 'Pronoun, Dual, Masculine, Dative',
    'p-d---mg-': 'Pronoun, Dual, Masculine, Genitive',
    'p-d---mn-': 'Pronoun, Dual, Masculine, Nominative',
    'p-p----a-': 'Pronoun, Plural, Accusative',
    'p-p----d-': 'Pronoun, Plural, Dative',
    'p-p----g-': 'Pronoun, Plural, Genitive',
    'p-p----n-': 'Pronoun, Plural, Nominative',
    'p-p---fa-': 'Pronoun, Plural, Feminine, Accusative',
    'p-p---fd-': 'Pronoun, Plural, Feminine, Dative',
    'p-p---fg-': 'Pronoun, Plural, Feminine, Genitive',
    'p-p---fn-': 'Pronoun, Plural, Feminine, Nominative',
    'p-p---ma-': 'Pronoun, Plural, Masculine, Accusative',
    'p-p---md-': 'Pronoun, Plural, Masculine, Dative',
    'p-p---mg-': 'Pronoun, Plural, Masculine, Genitive',
    'p-p---mn-': 'Pronoun, Plural, Masculine, Nominative',
    'p-p---mv-': 'Pronoun, Plural, Masculine, Vocative',
    'p-p---na-': 'Pronoun, Plural, Neuter, Accusative',
    'p-p---nd-': 'Pronoun, Plural, Neuter, Dative',
    'p-p---ng-': 'Pronoun, Plural, Neuter, Genitive',
    'p-p---nn-': 'Pronoun, Plural, Neuter, Nominative',
    'p-s----a-': 'Pronoun, Singular, Accusative',
    'p-s----d-': 'Pronoun, Singular, Dative',
    'p-s----g-': 'Pronoun, Singular, Genitive',
    'p-s----n-': 'Pronoun, Singular, Nominative',
    'p-s---fa-': 'Pronoun, Singular, Feminine, Accusative',
    'p-s---fd-': 'Pronoun, Singular, Feminine, Dative',
    'p-s---fg-': 'Pronoun, Singular, Feminine, Genitive',
    'p-s---fn-': 'Pronoun, Singular, Feminine, Nominative',
    'p-s---ma-': 'Pronoun, Singular, Masculine, Accusative',
    'p-s---md-': 'Pronoun, Singular, Masculine, Dative',
    'p-s---mg-': 'Pronoun, Singular, Masculine, Genitive',
    'p-s---mn-': 'Pronoun, Singular, Masculine, Nominative',
    'p-s---mv-': 'Pronoun, Singular, Masculine, Vocative',
    'p-s---na-': 'Pronoun, Singular, Neuter, Accusative',
    'p-s---nd-': 'Pronoun, Singular, Neuter, Dative',
    'p-s---ng-': 'Pronoun, Singular, Neuter, Genitive',
    'p-s---nn-': 'Pronoun, Singular, Neuter, Nominative',
    'p1p---ma-': 'Pronoun, First Person, Plural, Masculine, Accusative',
    'p1p---md-': 'Pronoun, First Person, Plural, Masculine, Dative',
    'p1p---mg-': 'Pronoun, First Person, Plural, Masculine, Genitive',
    'p1p---mn-': 'Pronoun, First Person, Plural, Masculine, Nominative',
    'p1p---mv-': 'Pronoun, First Person, Plural, Masculine, Vocative',
    'p1s---fa-': 'Pronoun, First Person, Singular, Feminine, Accusative',
    'p1s---fd-': 'Pronoun, First Person, Singular, Feminine, Dative',
    'p1s---fg-': 'Pronoun, First Person, Singular, Feminine, Genitive',
    'p1s---fn-': 'Pronoun, First Person, Singular, Feminine, Nominative',
    'p1s---ma-': 'Pronoun, First Person, Singular, Masculine, Accusative',
    'p1s---md-': 'Pronoun, First Person, Singular, Masculine, Dative',
    'p1s---mg-': 'Pronoun, First Person, Singular, Masculine, Genitive',
    'p1s---mn-': 'Pronoun, First Person, Singular, Masculine, Nominative',
    'p2p----a-': 'Pronoun, Second Person, Plural, Accusative',
    'p2p----d-': 'Pronoun, Second Person, Plural, Dative',
    'p2p----g-': 'Pronoun, Second Person, Plural, Genitive',
    'p2p----n-': 'Pronoun, Second Person, Plural, Nominative',
    'p2p---fd-': 'Pronoun, Second Person, Plural, Feminine, Dative',
    'p2p---ma-': 'Pronoun, Second Person, Plural, Masculine, Accusative',
    'p2p---md-': 'Pronoun, Second Person, Plural, Masculine, Dative',
    'p2p---mg-': 'Pronoun, Second Person, Plural, Masculine, Genitive',
    'p2p---mn-': 'Pronoun, Second Person, Plural, Masculine, Nominative',
    'p2s----a-': 'Pronoun, Second Person, Singular, Accusative',
    'p2s----d-': 'Pronoun, Second Person, Singular, Dative',
    'p2s----g-': 'Pronoun, Second Person, Singular, Genitive',
    'p2s----n-': 'Pronoun, Second Person, Singular, Nominative',
    'p2s---fa-': 'Pronoun, Second Person, Singular, Feminine, Accusative',
    'p2s---ma-': 'Pronoun, Second Person, Singular, Masculine, Accusative',
    'p2s---md-': 'Pronoun, Second Person, Singular, Masculine, Dative',
    'p2s---mg-': 'Pronoun, Second Person, Singular, Masculine, Genitive',
    'p2s---mn-': 'Pronoun, Second Person, Singular, Masculine, Nominative',
    'p3s---ma-': 'Pronoun, Third Person, Singular, Masculine, Accusative',
    'r--------': 'Adposition',
    'r-s---fv-': 'Adposition, Singular, Feminine, Vocative',
    'u--------': 'Punctuation',
    'v---na---': 'Verb, Infinitive, Active',
    'v--an----': 'Verb, Aorist, Infinitive',
    'v--ana---': 'Verb, Aorist, Infinitive, Active',
    'v--ane---': 'Verb, Aorist, Infinitive, Medio-Passive',
    'v--anm---': 'Verb, Aorist, Infinitive, Middle',
    'v--anp---': 'Verb, Aorist, Infinitive, Passive',
    'v--fn----': 'Verb, Future, Infinitive',
    'v--fna---': 'Verb, Future, Infinitive, Active',
    'v--fne---': 'Verb, Future, Infinitive, Medio-Passive',
    'v--fnm---': 'Verb, Future, Infinitive, Middle',
    'v--fnp---': 'Verb, Future, Infinitive, Passive',
    'v--pna---': 'Verb, Present, Infinitive, Active',
    'v--pne---': 'Verb, Present, Infinitive, Medio-Passive',
    'v--pnp---': 'Verb, Present, Infinitive, Passive',
    'v--pp-mg-': 'Verb, Present, Participle, Masculine, Genitive',
    'v--ppamg-': 'Verb, Present, Participle, Active, Masculine, Genitive',
    'v--ppamn-': 'Verb, Present, Participle, Active, Masculine, Nominative',
    'v--rn----': 'Verb, Perfect, Infinitive',
    'v--rna---': 'Verb, Perfect, Infinitive, Active',
    'v--rne---': 'Verb, Perfect, Infinitive, Medio-Passive',
    'v--rnp---': 'Verb, Perfect, Infinitive, Passive',
    'v--tne---': 'Verb, Future Perfect, Infinitive, Medio-Passive',
    'v-dapafd-': 'Verb, Dual, Aorist, Participle, Active, Feminine, Dative',
    'v-dapafn-': 'Verb, Dual, Aorist, Participle, Active, Feminine, Nominative',
    'v-dapama-': 'Verb, Dual, Aorist, Participle, Active, Masculine, Accusative',
    'v-dapamn-': 'Verb, Dual, Aorist, Participle, Active, Masculine, Nominative',
    'v-dapemn-': 'Verb, Dual, Aorist, Participle, Medio-Passive, Masculine, Nominative',
    'v-dapmfn-': 'Verb, Dual, Aorist, Participle, Middle, Feminine, Nominative',
    'v-dapmmn-': 'Verb, Dual, Aorist, Participle, Middle, Masculine, Nominative',
    'v-dappmn-': 'Verb, Dual, Aorist, Participle, Passive, Masculine, Nominative',
    'v-dfpamn-': 'Verb, Dual, Future, Participle, Active, Masculine, Nominative',
    'v-dppafd-': 'Verb, Dual, Present, Participle, Active, Feminine, Dative',
    'v-dppama-': 'Verb, Dual, Present, Participle, Active, Masculine, Accusative',
    'v-dppamn-': 'Verb, Dual, Present, Participle, Active, Masculine, Nominative',
    'v-dppana-': 'Verb, Dual, Present, Participle, Active, Neuter, Accusative',
    'v-dppema-': 'Verb, Dual, Present, Participle, Medio-Passive, Masculine, Accusative',
    'v-dppemn-': 'Verb, Dual, Present, Participle, Medio-Passive, Masculine, Nominative',
    'v-drpama-': 'Verb, Dual, Perfect, Participle, Active, Masculine, Accusative',
    'v-drpamn-': 'Verb, Dual, Perfect, Participle, Active, Masculine, Nominative',
    'v-drpemn-': 'Verb, Dual, Perfect, Participle, Medio-Passive, Masculine, Nominative',
    'v-p-pmma-': 'Verb, Plural, Participle, Middle, Masculine, Accusative',
    'v-pana---': 'Verb, Plural, Aorist, Infinitive, Active',
    'v-pap-mn-': 'Verb, Plural, Aorist, Participle, Masculine, Nominative',
    'v-papafn-': 'Verb, Plural, Aorist, Participle, Active, Feminine, Nominative',
    'v-papafv-': 'Verb, Plural, Aorist, Participle, Active, Feminine, Vocative',
    'v-papama-': 'Verb, Plural, Aorist, Participle, Active, Masculine, Accusative',
    'v-papamd-': 'Verb, Plural, Aorist, Participle, Active, Masculine, Dative',
    'v-papamg-': 'Verb, Plural, Aorist, Participle, Active, Masculine, Genitive',
    'v-papamn-': 'Verb, Plural, Aorist, Participle, Active, Masculine, Nominative',
    'v-papana-': 'Verb, Plural, Aorist, Participle, Active, Neuter, Accusative',
    'v-papang-': 'Verb, Plural, Aorist, Participle, Active, Neuter, Genitive',
    'v-papann-': 'Verb, Plural, Aorist, Participle, Active, Neuter, Nominative',
    'v-papefg-': 'Verb, Plural, Aorist, Participle, Medio-Passive, Feminine, Genitive',
    'v-papema-': 'Verb, Plural, Aorist, Participle, Medio-Passive, Masculine, Accusative',
    'v-papemn-': 'Verb, Plural, Aorist, Participle, Medio-Passive, Masculine, Nominative',
    'v-papena-': 'Verb, Plural, Aorist, Participle, Medio-Passive, Neuter, Accusative',
    'v-papmfa-': 'Verb, Plural, Aorist, Participle, Middle, Feminine, Accusative',
    'v-papmfd-': 'Verb, Plural, Aorist, Participle, Middle, Feminine, Dative',
    'v-papmfg-': 'Verb, Plural, Aorist, Participle, Middle, Feminine, Genitive',
    'v-papmfn-': 'Verb, Plural, Aorist, Participle, Middle, Feminine, Nominative',
    'v-papmma-': 'Verb, Plural, Aorist, Participle, Middle, Masculine, Accusative',
    'v-papmmd-': 'Verb, Plural, Aorist, Participle, Middle, Masculine, Dative',
    'v-papmmg-': 'Verb, Plural, Aorist, Participle, Middle, Masculine, Genitive',
    'v-papmmn-': 'Verb, Plural, Aorist, Participle, Middle, Masculine, Nominative',
    'v-papmna-': 'Verb, Plural, Aorist, Participle, Middle, Neuter, Accusative',
    'v-papmng-': 'Verb, Plural, Aorist, Participle, Middle, Neuter, Genitive',
    'v-papmnn-': 'Verb, Plural, Aorist, Participle, Middle, Neuter, Nominative',
    'v-pappfa-': 'Verb, Plural, Aorist, Participle, Passive, Feminine, Accusative',
    'v-pappfg-': 'Verb, Plural, Aorist, Participle, Passive, Feminine, Genitive',
    'v-pappfn-': 'Verb, Plural, Aorist, Participle, Passive, Feminine, Nominative',
    'v-pappma-': 'Verb, Plural, Aorist, Participle, Passive, Masculine, Accusative',
    'v-pappmd-': 'Verb, Plural, Aorist, Participle, Passive, Masculine, Dative',
    'v-pappmg-': 'Verb, Plural, Aorist, Participle, Passive, Masculine, Genitive',
    'v-pappmn-': 'Verb, Plural, Aorist, Participle, Passive, Masculine, Nominative',
    'v-pappna-': 'Verb, Plural, Aorist, Participle, Passive, Neuter, Accusative',
    'v-pappnd-': 'Verb, Plural, Aorist, Participle, Passive, Neuter, Dative',
    'v-pappng-': 'Verb, Plural, Aorist, Participle, Passive, Neuter, Genitive',
    'v-pappnn-': 'Verb, Plural, Aorist, Participle, Passive, Neuter, Nominative',
    'v-pfp-ma-': 'Verb, Plural, Future, Participle, Masculine, Accusative',
    'v-pfpafn-': 'Verb, Plural, Future, Participle, Active, Feminine, Nominative',
    'v-pfpama-': 'Verb, Plural, Future, Participle, Active, Masculine, Accusative',
    'v-pfpamg-': 'Verb, Plural, Future, Participle, Active, Masculine, Genitive',
    'v-pfpamn-': 'Verb, Plural, Future, Participle, Active, Masculine, Nominative',
    'v-pfpema-': 'Verb, Plural, Future, Participle, Medio-Passive, Masculine, Accusative',
    'v-pfpmfa-': 'Verb, Plural, Future, Participle, Middle, Feminine, Accusative',
    'v-pfpmfd-': 'Verb, Plural, Future, Participle, Middle, Feminine, Dative',
    'v-pfpmfg-': 'Verb, Plural, Future, Participle, Middle, Feminine, Genitive',
    'v-pfpmfn-': 'Verb, Plural, Future, Participle, Middle, Feminine, Nominative',
    'v-pfpmma-': 'Verb, Plural, Future, Participle, Middle, Masculine, Accusative',
    'v-pfpmmd-': 'Verb, Plural, Future, Participle, Middle, Masculine, Dative',
    'v-pfpmmg-': 'Verb, Plural, Future, Participle, Middle, Masculine, Genitive',
    'v-pfpmmn-': 'Verb, Plural, Future, Participle, Middle, Masculine, Nominative',
    'v-pfpmna-': 'Verb, Plural, Future, Participle, Middle, Neuter, Accusative',
    'v-pfpmnn-': 'Verb, Plural, Future, Participle, Middle, Neuter, Nominative',
    'v-ppp-ma-': 'Verb, Plural, Present, Participle, Masculine, Accusative',
    'v-ppp-mn-': 'Verb, Plural, Present, Participle, Masculine, Nominative',
    'v-ppp-mv-': 'Verb, Plural, Present, Participle, Masculine, Vocative',
    'v-pppafa-': 'Verb, Plural, Present, Participle, Active, Feminine, Accusative',
    'v-pppafd-': 'Verb, Plural, Present, Participle, Active, Feminine, Dative',
    'v-pppafg-': 'Verb, Plural, Present, Participle, Active, Feminine, Genitive',
    'v-pppafn-': 'Verb, Plural, Present, Participle, Active, Feminine, Nominative',
    'v-pppafv-': 'Verb, Plural, Present, Participle, Active, Feminine, Vocative',
    'v-pppama-': 'Verb, Plural, Present, Participle, Active, Masculine, Accusative',
    'v-pppamd-': 'Verb, Plural, Present, Participle, Active, Masculine, Dative',
    'v-pppamg-': 'Verb, Plural, Present, Participle, Active, Masculine, Genitive',
    'v-pppamn-': 'Verb, Plural, Present, Participle, Active, Masculine, Nominative',
    'v-pppamv-': 'Verb, Plural, Present, Participle, Active, Masculine, Vocative',
    'v-pppana-': 'Verb, Plural, Present, Participle, Active, Neuter, Accusative',
    'v-pppand-': 'Verb, Plural, Present, Participle, Active, Neuter, Dative',
    'v-pppang-': 'Verb, Plural, Present, Participle, Active, Neuter, Genitive',
    'v-pppann-': 'Verb, Plural, Present, Participle, Active, Neuter, Nominative',
    'v-pppefa-': 'Verb, Plural, Present, Participle, Medio-Passive, Feminine, Accusative',
    'v-pppefd-': 'Verb, Plural, Present, Participle, Medio-Passive, Feminine, Dative',
    'v-pppefg-': 'Verb, Plural, Present, Participle, Medio-Passive, Feminine, Genitive',
    'v-pppefn-': 'Verb, Plural, Present, Participle, Medio-Passive, Feminine, Nominative',
    'v-pppema-': 'Verb, Plural, Present, Participle, Medio-Passive, Masculine, Accusative',
    'v-pppemd-': 'Verb, Plural, Present, Participle, Medio-Passive, Masculine, Dative',
    'v-pppemg-': 'Verb, Plural, Present, Participle, Medio-Passive, Masculine, Genitive',
    'v-pppemn-': 'Verb, Plural, Present, Participle, Medio-Passive, Masculine, Nominative',
    'v-pppena-': 'Verb, Plural, Present, Participle, Medio-Passive, Neuter, Accusative',
    'v-pppend-': 'Verb, Plural, Present, Participle, Medio-Passive, Neuter, Dative',
    'v-pppeng-': 'Verb, Plural, Present, Participle, Medio-Passive, Neuter, Genitive',
    'v-pppenn-': 'Verb, Plural, Present, Participle, Medio-Passive, Neuter, Nominative',
    'v-ppppfg-': 'Verb, Plural, Present, Participle, Passive, Feminine, Genitive',
    'v-ppppma-': 'Verb, Plural, Present, Participle, Passive, Masculine, Accusative',
    'v-ppppmg-': 'Verb, Plural, Present, Participle, Passive, Masculine, Genitive',
    'v-ppppmn-': 'Verb, Plural, Present, Participle, Passive, Masculine, Nominative',
    'v-prp-fn-': 'Verb, Plural, Perfect, Participle, Feminine, Nominative',
    'v-prp-mn-': 'Verb, Plural, Perfect, Participle, Masculine, Nominative',
    'v-prp-nd-': 'Verb, Plural, Perfect, Participle, Neuter, Dative',
    'v-prp-nn-': 'Verb, Plural, Perfect, Participle, Neuter, Nominative',
    'v-prpafa-': 'Verb, Plural, Perfect, Participle, Active, Feminine, Accusative',
    'v-prpafn-': 'Verb, Plural, Perfect, Participle, Active, Feminine, Nominative',
    'v-prpama-': 'Verb, Plural, Perfect, Participle, Active, Masculine, Accusative',
    'v-prpamd-': 'Verb, Plural, Perfect, Participle, Active, Masculine, Dative',
    'v-prpamg-': 'Verb, Plural, Perfect, Participle, Active, Masculine, Genitive',
    'v-prpamn-': 'Verb, Plural, Perfect, Participle, Active, Masculine, Nominative',
    'v-prpana-': 'Verb, Plural, Perfect, Participle, Active, Neuter, Accusative',
    'v-prpand-': 'Verb, Plural, Perfect, Participle, Active, Neuter, Dative',
    'v-prpang-': 'Verb, Plural, Perfect, Participle, Active, Neuter, Genitive',
    'v-prpann-': 'Verb, Plural, Perfect, Participle, Active, Neuter, Nominative',
    'v-prpefa-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Feminine, Accusative',
    'v-prpefd-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Feminine, Dative',
    'v-prpefg-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Feminine, Genitive',
    'v-prpefn-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Feminine, Nominative',
    'v-prpema-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Masculine, Accusative',
    'v-prpemd-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Masculine, Dative',
    'v-prpemg-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Masculine, Genitive',
    'v-prpemn-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Masculine, Nominative',
    'v-prpena-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Neuter, Accusative',
    'v-prpend-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Neuter, Dative',
    'v-prpeng-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Neuter, Genitive',
    'v-prpenn-': 'Verb, Plural, Perfect, Participle, Medio-Passive, Neuter, Nominative',
    'v-prppfn-': 'Verb, Plural, Perfect, Participle, Passive, Feminine, Nominative',
    'v-prppmn-': 'Verb, Plural, Perfect, Participle, Passive, Masculine, Nominative',
    'v-saiamn-': 'Verb, Singular, Aorist, Indicative, Active, Masculine, Nominative',
    'v-samp---': 'Verb, Singular, Aorist, Imperative, Passive',
    'v-sap-fn-': 'Verb, Singular, Aorist, Participle, Feminine, Nominative',
    'v-sap-mn-': 'Verb, Singular, Aorist, Participle, Masculine, Nominative',
    'v-sapafa-': 'Verb, Singular, Aorist, Participle, Active, Feminine, Accusative',
    'v-sapafd-': 'Verb, Singular, Aorist, Participle, Active, Feminine, Dative',
    'v-sapafg-': 'Verb, Singular, Aorist, Participle, Active, Feminine, Genitive',
    'v-sapafn-': 'Verb, Singular, Aorist, Participle, Active, Feminine, Nominative',
    'v-sapafv-': 'Verb, Singular, Aorist, Participle, Active, Feminine, Vocative',
    'v-sapama-': 'Verb, Singular, Aorist, Participle, Active, Masculine, Accusative',
    'v-sapamd-': 'Verb, Singular, Aorist, Participle, Active, Masculine, Dative',
    'v-sapamg-': 'Verb, Singular, Aorist, Participle, Active, Masculine, Genitive',
    'v-sapamn-': 'Verb, Singular, Aorist, Participle, Active, Masculine, Nominative',
    'v-sapamv-': 'Verb, Singular, Aorist, Participle, Active, Masculine, Vocative',
    'v-sapana-': 'Verb, Singular, Aorist, Participle, Active, Neuter, Accusative',
    'v-sapang-': 'Verb, Singular, Aorist, Participle, Active, Neuter, Genitive',
    'v-sapann-': 'Verb, Singular, Aorist, Participle, Active, Neuter, Nominative',
    'v-sapanv-': 'Verb, Singular, Aorist, Participle, Active, Neuter, Vocative',
    'v-sapefa-': 'Verb, Singular, Aorist, Participle, Medio-Passive, Feminine, Accusative',
    'v-sapefn-': 'Verb, Singular, Aorist, Participle, Medio-Passive, Feminine, Nominative',
    'v-sapema-': 'Verb, Singular, Aorist, Participle, Medio-Passive, Masculine, Accusative',
    'v-sapemg-': 'Verb, Singular, Aorist, Participle, Medio-Passive, Masculine, Genitive',
    'v-sapemn-': 'Verb, Singular, Aorist, Participle, Medio-Passive, Masculine, Nominative',
    'v-sapmfa-': 'Verb, Singular, Aorist, Participle, Middle, Feminine, Accusative',
    'v-sapmfg-': 'Verb, Singular, Aorist, Participle, Middle, Feminine, Genitive',
    'v-sapmfn-': 'Verb, Singular, Aorist, Participle, Middle, Feminine, Nominative',
    'v-sapmma-': 'Verb, Singular, Aorist, Participle, Middle, Masculine, Accusative',
    'v-sapmmd-': 'Verb, Singular, Aorist, Participle, Middle, Masculine, Dative',
    'v-sapmmg-': 'Verb, Singular, Aorist, Participle, Middle, Masculine, Genitive',
    'v-sapmmn-': 'Verb, Singular, Aorist, Participle, Middle, Masculine, Nominative',
    'v-sapmna-': 'Verb, Singular, Aorist, Participle, Middle, Neuter, Accusative',
    'v-sapmng-': 'Verb, Singular, Aorist, Participle, Middle, Neuter, Genitive',
    'v-sapmnn-': 'Verb, Singular, Aorist, Participle, Middle, Neuter, Nominative',
    'v-sappfa-': 'Verb, Singular, Aorist, Participle, Passive, Feminine, Accusative',
    'v-sappfg-': 'Verb, Singular, Aorist, Participle, Passive, Feminine, Genitive',
    'v-sappfn-': 'Verb, Singular, Aorist, Participle, Passive, Feminine, Nominative',
    'v-sappma-': 'Verb, Singular, Aorist, Participle, Passive, Masculine, Accusative',
    'v-sappmd-': 'Verb, Singular, Aorist, Participle, Passive, Masculine, Dative',
    'v-sappmg-': 'Verb, Singular, Aorist, Participle, Passive, Masculine, Genitive',
    'v-sappmn-': 'Verb, Singular, Aorist, Participle, Passive, Masculine, Nominative',
    'v-sappmv-': 'Verb, Singular, Aorist, Participle, Passive, Masculine, Vocative',
    'v-sappna-': 'Verb, Singular, Aorist, Participle, Passive, Neuter, Accusative',
    'v-sappng-': 'Verb, Singular, Aorist, Participle, Passive, Neuter, Genitive',
    'v-sappnn-': 'Verb, Singular, Aorist, Participle, Passive, Neuter, Nominative',
    'v-sappnv-': 'Verb, Singular, Aorist, Participle, Passive, Neuter, Vocative',
    'v-sfp-ma-': 'Verb, Singular, Future, Participle, Masculine, Accusative',
    'v-sfpafd-': 'Verb, Singular, Future, Participle, Active, Feminine, Dative',
    'v-sfpafn-': 'Verb, Singular, Future, Participle, Active, Feminine, Nominative',
    'v-sfpama-': 'Verb, Singular, Future, Participle, Active, Masculine, Accusative',
    'v-sfpamd-': 'Verb, Singular, Future, Participle, Active, Masculine, Dative',
    'v-sfpamg-': 'Verb, Singular, Future, Participle, Active, Masculine, Genitive',
    'v-sfpamn-': 'Verb, Singular, Future, Participle, Active, Masculine, Nominative',
    'v-sfpemn-': 'Verb, Singular, Future, Participle, Medio-Passive, Masculine, Nominative',
    'v-sfpmfa-': 'Verb, Singular, Future, Participle, Middle, Feminine, Accusative',
    'v-sfpmfg-': 'Verb, Singular, Future, Participle, Middle, Feminine, Genitive',
    'v-sfpmfn-': 'Verb, Singular, Future, Participle, Middle, Feminine, Nominative',
    'v-sfpmma-': 'Verb, Singular, Future, Participle, Middle, Masculine, Accusative',
    'v-sfpmmg-': 'Verb, Singular, Future, Participle, Middle, Masculine, Genitive',
    'v-sfpmmn-': 'Verb, Singular, Future, Participle, Middle, Masculine, Nominative',
    'v-sfpmna-': 'Verb, Singular, Future, Participle, Middle, Neuter, Accusative',
    'v-spiamn-': 'Verb, Singular, Present, Indicative, Active, Masculine, Nominative',
    'v-spiemn-': 'Verb, Singular, Present, Indicative, Medio-Passive, Masculine, Nominative',
    'v-spna---': 'Verb, Singular, Present, Infinitive, Active',
    'v-spp-fn-': 'Verb, Singular, Present, Participle, Feminine, Nominative',
    'v-spp-mn-': 'Verb, Singular, Present, Participle, Masculine, Nominative',
    'v-spp-na-': 'Verb, Singular, Present, Participle, Neuter, Accusative',
    'v-spp-nn-': 'Verb, Singular, Present, Participle, Neuter, Nominative',
    'v-sppa---': 'Verb, Singular, Present, Participle, Active',
    'v-sppafa-': 'Verb, Singular, Present, Participle, Active, Feminine, Accusative',
    'v-sppafd-': 'Verb, Singular, Present, Participle, Active, Feminine, Dative',
    'v-sppafg-': 'Verb, Singular, Present, Participle, Active, Feminine, Genitive',
    'v-sppafn-': 'Verb, Singular, Present, Participle, Active, Feminine, Nominative',
    'v-sppafv-': 'Verb, Singular, Present, Participle, Active, Feminine, Vocative',
    'v-sppama-': 'Verb, Singular, Present, Participle, Active, Masculine, Accusative',
    'v-sppamd-': 'Verb, Singular, Present, Participle, Active, Masculine, Dative',
    'v-sppamg-': 'Verb, Singular, Present, Participle, Active, Masculine, Genitive',
    'v-sppamn-': 'Verb, Singular, Present, Participle, Active, Masculine, Nominative',
    'v-sppamv-': 'Verb, Singular, Present, Participle, Active, Masculine, Vocative',
    'v-sppana-': 'Verb, Singular, Present, Participle, Active, Neuter, Accusative',
    'v-sppand-': 'Verb, Singular, Present, Participle, Active, Neuter, Dative',
    'v-sppang-': 'Verb, Singular, Present, Participle, Active, Neuter, Genitive',
    'v-sppann-': 'Verb, Singular, Present, Participle, Active, Neuter, Nominative',
    'v-sppanv-': 'Verb, Singular, Present, Participle, Active, Neuter, Vocative',
    'v-sppefa-': 'Verb, Singular, Present, Participle, Medio-Passive, Feminine, Accusative',
    'v-sppefd-': 'Verb, Singular, Present, Participle, Medio-Passive, Feminine, Dative',
    'v-sppefg-': 'Verb, Singular, Present, Participle, Medio-Passive, Feminine, Genitive',
    'v-sppefn-': 'Verb, Singular, Present, Participle, Medio-Passive, Feminine, Nominative',
    'v-sppema-': 'Verb, Singular, Present, Participle, Medio-Passive, Masculine, Accusative',
    'v-sppemd-': 'Verb, Singular, Present, Participle, Medio-Passive, Masculine, Dative',
    'v-sppemg-': 'Verb, Singular, Present, Participle, Medio-Passive, Masculine, Genitive',
    'v-sppemn-': 'Verb, Singular, Present, Participle, Medio-Passive, Masculine, Nominative',
    'v-sppena-': 'Verb, Singular, Present, Participle, Medio-Passive, Neuter, Accusative',
    'v-sppend-': 'Verb, Singular, Present, Participle, Medio-Passive, Neuter, Dative',
    'v-sppeng-': 'Verb, Singular, Present, Participle, Medio-Passive, Neuter, Genitive',
    'v-sppenn-': 'Verb, Singular, Present, Participle, Medio-Passive, Neuter, Nominative',
    'v-spppfa-': 'Verb, Singular, Present, Participle, Passive, Feminine, Accusative',
    'v-spppmn-': 'Verb, Singular, Present, Participle, Passive, Masculine, Nominative',
    'v-srp-mn-': 'Verb, Singular, Perfect, Participle, Masculine, Nominative',
    'v-srp-na-': 'Verb, Singular, Perfect, Participle, Neuter, Accusative',
    'v-srpafa-': 'Verb, Singular, Perfect, Participle, Active, Feminine, Accusative',
    'v-srpafg-': 'Verb, Singular, Perfect, Participle, Active, Feminine, Genitive',
    'v-srpafn-': 'Verb, Singular, Perfect, Participle, Active, Feminine, Nominative',
    'v-srpama-': 'Verb, Singular, Perfect, Participle, Active, Masculine, Accusative',
    'v-srpamd-': 'Verb, Singular, Perfect, Participle, Active, Masculine, Dative',
    'v-srpamg-': 'Verb, Singular, Perfect, Participle, Active, Masculine, Genitive',
    'v-srpamn-': 'Verb, Singular, Perfect, Participle, Active, Masculine, Nominative',
    'v-srpana-': 'Verb, Singular, Perfect, Participle, Active, Neuter, Accusative',
    'v-srpand-': 'Verb, Singular, Perfect, Participle, Active, Neuter, Dative',
    'v-srpang-': 'Verb, Singular, Perfect, Participle, Active, Neuter, Genitive',
    'v-srpann-': 'Verb, Singular, Perfect, Participle, Active, Neuter, Nominative',
    'v-srpefa-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Feminine, Accusative',
    'v-srpefd-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Feminine, Dative',
    'v-srpefg-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Feminine, Genitive',
    'v-srpefn-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Feminine, Nominative',
    'v-srpema-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Masculine, Accusative',
    'v-srpemd-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Masculine, Dative',
    'v-srpemg-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Masculine, Genitive',
    'v-srpemn-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Masculine, Nominative',
    'v-srpena-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Neuter, Accusative',
    'v-srpend-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Neuter, Dative',
    'v-srpeng-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Neuter, Genitive',
    'v-srpenn-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Neuter, Nominative',
    'v-srpenv-': 'Verb, Singular, Perfect, Participle, Medio-Passive, Neuter, Vocative',
    'v-srppfn-': 'Verb, Singular, Perfect, Participle, Passive, Feminine, Nominative',
    'v-srppmn-': 'Verb, Singular, Perfect, Participle, Passive, Masculine, Nominative',
    'v1-pia---': 'Verb, First Person, Present, Indicative, Active',
    'v1pai----': 'Verb, First Person, Plural, Aorist, Indicative',
    'v1paia---': 'Verb, First Person, Plural, Aorist, Indicative, Active',
    'v1paim---': 'Verb, First Person, Plural, Aorist, Indicative, Middle',
    'v1paip---': 'Verb, First Person, Plural, Aorist, Indicative, Passive',
    'v1paoa---': 'Verb, First Person, Plural, Aorist, Optative, Active',
    'v1paom---': 'Verb, First Person, Plural, Aorist, Optative, Middle',
    'v1paop---': 'Verb, First Person, Plural, Aorist, Optative, Passive',
    'v1pas----': 'Verb, First Person, Plural, Aorist, Subjunctive',
    'v1pasa---': 'Verb, First Person, Plural, Aorist, Subjunctive, Active',
    'v1pase---': 'Verb, First Person, Plural, Aorist, Subjunctive, Medio-Passive',
    'v1pasm---': 'Verb, First Person, Plural, Aorist, Subjunctive, Middle',
    'v1pasp---': 'Verb, First Person, Plural, Aorist, Subjunctive, Passive',
    'v1pfia---': 'Verb, First Person, Plural, Future, Indicative, Active',
    'v1pfim---': 'Verb, First Person, Plural, Future, Indicative, Middle',
    'v1piia---': 'Verb, First Person, Plural, Imperfect, Indicative, Active',
    'v1piie---': 'Verb, First Person, Plural, Imperfect, Indicative, Medio-Passive',
    'v1pli----': 'Verb, First Person, Plural, Plusquamperfect, Indicative',
    'v1plie---': 'Verb, First Person, Plural, Plusquamperfect, Indicative, Medio-Passive',
    'v1ppi----': 'Verb, First Person, Plural, Present, Indicative',
    'v1ppia---': 'Verb, First Person, Plural, Present, Indicative, Active',
    'v1ppid---': 'Verb, First Person, Plural, Present, Indicative, Voice=d',
    'v1ppie---': 'Verb, First Person, Plural, Present, Indicative, Medio-Passive',
    'v1ppoa---': 'Verb, First Person, Plural, Present, Optative, Active',
    'v1ppoe---': 'Verb, First Person, Plural, Present, Optative, Medio-Passive',
    'v1ppsa---': 'Verb, First Person, Plural, Present, Subjunctive, Active',
    'v1ppse---': 'Verb, First Person, Plural, Present, Subjunctive, Medio-Passive',
    'v1pria---': 'Verb, First Person, Plural, Perfect, Indicative, Active',
    'v1prie---': 'Verb, First Person, Plural, Perfect, Indicative, Medio-Passive',
    'v1prsa---': 'Verb, First Person, Plural, Perfect, Subjunctive, Active',
    'v1prse---': 'Verb, First Person, Plural, Perfect, Subjunctive, Medio-Passive',
    'v1ptia---': 'Verb, First Person, Plural, Future Perfect, Indicative, Active',
    'v1ptie---': 'Verb, First Person, Plural, Future Perfect, Indicative, Medio-Passive',
    'v1s-sa---': 'Verb, First Person, Singular, Subjunctive, Active',
    'v1saia---': 'Verb, First Person, Singular, Aorist, Indicative, Active',
    'v1saie---': 'Verb, First Person, Singular, Aorist, Indicative, Medio-Passive',
    'v1saim---': 'Verb, First Person, Singular, Aorist, Indicative, Middle',
    'v1saip---': 'Verb, First Person, Singular, Aorist, Indicative, Passive',
    'v1saoa---': 'Verb, First Person, Singular, Aorist, Optative, Active',
    'v1saoe---': 'Verb, First Person, Singular, Aorist, Optative, Medio-Passive',
    'v1saom---': 'Verb, First Person, Singular, Aorist, Optative, Middle',
    'v1saop---': 'Verb, First Person, Singular, Aorist, Optative, Passive',
    'v1sas----': 'Verb, First Person, Singular, Aorist, Subjunctive',
    'v1sasa---': 'Verb, First Person, Singular, Aorist, Subjunctive, Active',
    'v1sase---': 'Verb, First Person, Singular, Aorist, Subjunctive, Medio-Passive',
    'v1sasm---': 'Verb, First Person, Singular, Aorist, Subjunctive, Middle',
    'v1sasp---': 'Verb, First Person, Singular, Aorist, Subjunctive, Passive',
    'v1sfi----': 'Verb, First Person, Singular, Future, Indicative',
    'v1sfia---': 'Verb, First Person, Singular, Future, Indicative, Active',
    'v1sfie---': 'Verb, First Person, Singular, Future, Indicative, Medio-Passive',
    'v1sfim---': 'Verb, First Person, Singular, Future, Indicative, Middle',
    'v1sfip---': 'Verb, First Person, Singular, Future, Indicative, Passive',
    'v1sfoa---': 'Verb, First Person, Singular, Future, Optative, Active',
    'v1sfom---': 'Verb, First Person, Singular, Future, Optative, Middle',
    'v1siia---': 'Verb, First Person, Singular, Imperfect, Indicative, Active',
    'v1siie---': 'Verb, First Person, Singular, Imperfect, Indicative, Medio-Passive',
    'v1slia---': 'Verb, First Person, Singular, Plusquamperfect, Indicative, Active',
    'v1slie---': 'Verb, First Person, Singular, Plusquamperfect, Indicative, Medio-Passive',
    'v1spia---': 'Verb, First Person, Singular, Present, Indicative, Active',
    'v1spie---': 'Verb, First Person, Singular, Present, Indicative, Medio-Passive',
    'v1spoa---': 'Verb, First Person, Singular, Present, Optative, Active',
    'v1spoe---': 'Verb, First Person, Singular, Present, Optative, Medio-Passive',
    'v1spsa---': 'Verb, First Person, Singular, Present, Subjunctive, Active',
    'v1spse---': 'Verb, First Person, Singular, Present, Subjunctive, Medio-Passive',
    'v1spsp---': 'Verb, First Person, Singular, Present, Subjunctive, Passive',
    'v1sria---': 'Verb, First Person, Singular, Perfect, Indicative, Active',
    'v1srie---': 'Verb, First Person, Singular, Perfect, Indicative, Medio-Passive',
    'v1srsa---': 'Verb, First Person, Singular, Perfect, Subjunctive, Active',
    'v1stie---': 'Verb, First Person, Singular, Future Perfect, Indicative, Medio-Passive',
    'v1stim---': 'Verb, First Person, Singular, Future Perfect, Indicative, Middle',
    'v2-pma---': 'Verb, Second Person, Present, Imperative, Active',
    'v2daia---': 'Verb, Second Person, Dual, Aorist, Indicative, Active',
    'v2dasa---': 'Verb, Second Person, Dual, Aorist, Subjunctive, Active',
    'v2dfia---': 'Verb, Second Person, Dual, Future, Indicative, Active',
    'v2dfim---': 'Verb, Second Person, Dual, Future, Indicative, Middle',
    'v2dpia---': 'Verb, Second Person, Dual, Present, Indicative, Active',
    'v2dpie---': 'Verb, Second Person, Dual, Present, Indicative, Medio-Passive',
    'v2dpma---': 'Verb, Second Person, Dual, Present, Imperative, Active',
    'v2dpme---': 'Verb, Second Person, Dual, Present, Imperative, Medio-Passive',
    'v2paia---': 'Verb, Second Person, Plural, Aorist, Indicative, Active',
    'v2paie---': 'Verb, Second Person, Plural, Aorist, Indicative, Medio-Passive',
    'v2paim---': 'Verb, Second Person, Plural, Aorist, Indicative, Middle',
    'v2pama---': 'Verb, Second Person, Plural, Aorist, Imperative, Active',
    'v2pame---': 'Verb, Second Person, Plural, Aorist, Imperative, Medio-Passive',
    'v2pamm---': 'Verb, Second Person, Plural, Aorist, Imperative, Middle',
    'v2paoa---': 'Verb, Second Person, Plural, Aorist, Optative, Active',
    'v2paom---': 'Verb, Second Person, Plural, Aorist, Optative, Middle',
    'v2pasa---': 'Verb, Second Person, Plural, Aorist, Subjunctive, Active',
    'v2pase---': 'Verb, Second Person, Plural, Aorist, Subjunctive, Medio-Passive',
    'v2pasm---': 'Verb, Second Person, Plural, Aorist, Subjunctive, Middle',
    'v2pfia---': 'Verb, Second Person, Plural, Future, Indicative, Active',
    'v2pfie---': 'Verb, Second Person, Plural, Future, Indicative, Medio-Passive',
    'v2pfim---': 'Verb, Second Person, Plural, Future, Indicative, Middle',
    'v2piia---': 'Verb, Second Person, Plural, Imperfect, Indicative, Active',
    'v2piie---': 'Verb, Second Person, Plural, Imperfect, Indicative, Medio-Passive',
    'v2ppia---': 'Verb, Second Person, Plural, Present, Indicative, Active',
    'v2ppie---': 'Verb, Second Person, Plural, Present, Indicative, Medio-Passive',
    'v2ppma---': 'Verb, Second Person, Plural, Present, Imperative, Active',
    'v2ppme---': 'Verb, Second Person, Plural, Present, Imperative, Medio-Passive',
    'v2ppoa---': 'Verb, Second Person, Plural, Present, Optative, Active',
    'v2ppoe---': 'Verb, Second Person, Plural, Present, Optative, Medio-Passive',
    'v2ppsa---': 'Verb, Second Person, Plural, Present, Subjunctive, Active',
    'v2pria---': 'Verb, Second Person, Plural, Perfect, Indicative, Active',
    'v2prma---': 'Verb, Second Person, Plural, Perfect, Imperative, Active',
    'v2prme---': 'Verb, Second Person, Plural, Perfect, Imperative, Medio-Passive',
    'v2proa---': 'Verb, Second Person, Plural, Perfect, Optative, Active',
    'v2saia---': 'Verb, Second Person, Singular, Aorist, Indicative, Active',
    'v2saie---': 'Verb, Second Person, Singular, Aorist, Indicative, Medio-Passive',
    'v2saim---': 'Verb, Second Person, Singular, Aorist, Indicative, Middle',
    'v2saip---': 'Verb, Second Person, Singular, Aorist, Indicative, Passive',
    'v2sama---': 'Verb, Second Person, Singular, Aorist, Imperative, Active',
    'v2same---': 'Verb, Second Person, Singular, Aorist, Imperative, Medio-Passive',
    'v2samm---': 'Verb, Second Person, Singular, Aorist, Imperative, Middle',
    'v2samp---': 'Verb, Second Person, Singular, Aorist, Imperative, Passive',
    'v2saoa---': 'Verb, Second Person, Singular, Aorist, Optative, Active',
    'v2saoe---': 'Verb, Second Person, Singular, Aorist, Optative, Medio-Passive',
    'v2saom---': 'Verb, Second Person, Singular, Aorist, Optative, Middle',
    'v2saop---': 'Verb, Second Person, Singular, Aorist, Optative, Passive',
    'v2sasa---': 'Verb, Second Person, Singular, Aorist, Subjunctive, Active',
    'v2sase---': 'Verb, Second Person, Singular, Aorist, Subjunctive, Medio-Passive',
    'v2sasm---': 'Verb, Second Person, Singular, Aorist, Subjunctive, Middle',
    'v2sasp---': 'Verb, Second Person, Singular, Aorist, Subjunctive, Passive',
    'v2sfi----': 'Verb, Second Person, Singular, Future, Indicative',
    'v2sfia---': 'Verb, Second Person, Singular, Future, Indicative, Active',
    'v2sfie---': 'Verb, Second Person, Singular, Future, Indicative, Medio-Passive',
    'v2sfim---': 'Verb, Second Person, Singular, Future, Indicative, Middle',
    'v2siia---': 'Verb, Second Person, Singular, Imperfect, Indicative, Active',
    'v2siie---': 'Verb, Second Person, Singular, Imperfect, Indicative, Medio-Passive',
    'v2siip---': 'Verb, Second Person, Singular, Imperfect, Indicative, Passive',
    'v2slie---': 'Verb, Second Person, Singular, Plusquamperfect, Indicative, Medio-Passive',
    'v2spia---': 'Verb, Second Person, Singular, Present, Indicative, Active',
    'v2spie---': 'Verb, Second Person, Singular, Present, Indicative, Medio-Passive',
    'v2spma---': 'Verb, Second Person, Singular, Present, Imperative, Active',
    'v2spme---': 'Verb, Second Person, Singular, Present, Imperative, Medio-Passive',
    'v2spoa---': 'Verb, Second Person, Singular, Present, Optative, Active',
    'v2spoe---': 'Verb, Second Person, Singular, Present, Optative, Medio-Passive',
    'v2spsa---': 'Verb, Second Person, Singular, Present, Subjunctive, Active',
    'v2spse---': 'Verb, Second Person, Singular, Present, Subjunctive, Medio-Passive',
    'v2sria---': 'Verb, Second Person, Singular, Perfect, Indicative, Active',
    'v2srie---': 'Verb, Second Person, Singular, Perfect, Indicative, Medio-Passive',
    'v2srma---': 'Verb, Second Person, Singular, Perfect, Imperative, Active',
    'v2srme---': 'Verb, Second Person, Singular, Perfect, Imperative, Medio-Passive',
    'v2sroa---': 'Verb, Second Person, Singular, Perfect, Optative, Active',
    'v2srsa---': 'Verb, Second Person, Singular, Perfect, Subjunctive, Active',
    'v2stie---': 'Verb, Second Person, Singular, Future Perfect, Indicative, Medio-Passive',
    'v3-aia---': 'Verb, Third Person, Aorist, Indicative, Active',
    'v3daia---': 'Verb, Third Person, Dual, Aorist, Indicative, Active',
    'v3daim---': 'Verb, Third Person, Dual, Aorist, Indicative, Middle',
    'v3daip---': 'Verb, Third Person, Dual, Aorist, Indicative, Passive',
    'v3daoa---': 'Verb, Third Person, Dual, Aorist, Optative, Active',
    'v3dasa---': 'Verb, Third Person, Dual, Aorist, Subjunctive, Active',
    'v3dasp---': 'Verb, Third Person, Dual, Aorist, Subjunctive, Passive',
    'v3dfia---': 'Verb, Third Person, Dual, Future, Indicative, Active',
    'v3dfim---': 'Verb, Third Person, Dual, Future, Indicative, Middle',
    'v3diia---': 'Verb, Third Person, Dual, Imperfect, Indicative, Active',
    'v3diie---': 'Verb, Third Person, Dual, Imperfect, Indicative, Medio-Passive',
    'v3dlia---': 'Verb, Third Person, Dual, Plusquamperfect, Indicative, Active',
    'v3dlie---': 'Verb, Third Person, Dual, Plusquamperfect, Indicative, Medio-Passive',
    'v3dlim---': 'Verb, Third Person, Dual, Plusquamperfect, Indicative, Middle',
    'v3dlip---': 'Verb, Third Person, Dual, Plusquamperfect, Indicative, Passive',
    'v3dpia---': 'Verb, Third Person, Dual, Present, Indicative, Active',
    'v3dpie---': 'Verb, Third Person, Dual, Present, Indicative, Medio-Passive',
    'v3dpme---': 'Verb, Third Person, Dual, Present, Imperative, Medio-Passive',
    'v3dpsa---': 'Verb, Third Person, Dual, Present, Subjunctive, Active',
    'v3dria---': 'Verb, Third Person, Dual, Perfect, Indicative, Active',
    'v3pai----': 'Verb, Third Person, Plural, Aorist, Indicative',
    'v3paia---': 'Verb, Third Person, Plural, Aorist, Indicative, Active',
    'v3paie---': 'Verb, Third Person, Plural, Aorist, Indicative, Medio-Passive',
    'v3paim---': 'Verb, Third Person, Plural, Aorist, Indicative, Middle',
    'v3paip---': 'Verb, Third Person, Plural, Aorist, Indicative, Passive',
    'v3pama---': 'Verb, Third Person, Plural, Aorist, Imperative, Active',
    'v3pamm---': 'Verb, Third Person, Plural, Aorist, Imperative, Middle',
    'v3paoa---': 'Verb, Third Person, Plural, Aorist, Optative, Active',
    'v3paoe---': 'Verb, Third Person, Plural, Aorist, Optative, Medio-Passive',
    'v3paom---': 'Verb, Third Person, Plural, Aorist, Optative, Middle',
    'v3paop---': 'Verb, Third Person, Plural, Aorist, Optative, Passive',
    'v3pasa---': 'Verb, Third Person, Plural, Aorist, Subjunctive, Active',
    'v3pase---': 'Verb, Third Person, Plural, Aorist, Subjunctive, Medio-Passive',
    'v3pasm---': 'Verb, Third Person, Plural, Aorist, Subjunctive, Middle',
    'v3pasp---': 'Verb, Third Person, Plural, Aorist, Subjunctive, Passive',
    'v3pfia---': 'Verb, Third Person, Plural, Future, Indicative, Active',
    'v3pfie---': 'Verb, Third Person, Plural, Future, Indicative, Medio-Passive',
    'v3pfim---': 'Verb, Third Person, Plural, Future, Indicative, Middle',
    'v3pfip---': 'Verb, Third Person, Plural, Future, Indicative, Passive',
    'v3pfom---': 'Verb, Third Person, Plural, Future, Optative, Middle',
    'v3pii----': 'Verb, Third Person, Plural, Imperfect, Indicative',
    'v3piia---': 'Verb, Third Person, Plural, Imperfect, Indicative, Active',
    'v3piie---': 'Verb, Third Person, Plural, Imperfect, Indicative, Medio-Passive',
    'v3piip---': 'Verb, Third Person, Plural, Imperfect, Indicative, Passive',
    'v3plia---': 'Verb, Third Person, Plural, Plusquamperfect, Indicative, Active',
    'v3plie---': 'Verb, Third Person, Plural, Plusquamperfect, Indicative, Medio-Passive',
    'v3plim---': 'Verb, Third Person, Plural, Plusquamperfect, Indicative, Middle',
    'v3plip---': 'Verb, Third Person, Plural, Plusquamperfect, Indicative, Passive',
    'v3ppia---': 'Verb, Third Person, Plural, Present, Indicative, Active',
    'v3ppie---': 'Verb, Third Person, Plural, Present, Indicative, Medio-Passive',
    'v3ppip---': 'Verb, Third Person, Plural, Present, Indicative, Passive',
    'v3ppma---': 'Verb, Third Person, Plural, Present, Imperative, Active',
    'v3ppme---': 'Verb, Third Person, Plural, Present, Imperative, Medio-Passive',
    'v3ppoa---': 'Verb, Third Person, Plural, Present, Optative, Active',
    'v3ppoe---': 'Verb, Third Person, Plural, Present, Optative, Medio-Passive',
    'v3ppsa---': 'Verb, Third Person, Plural, Present, Subjunctive, Active',
    'v3ppse---': 'Verb, Third Person, Plural, Present, Subjunctive, Medio-Passive',
    'v3pri----': 'Verb, Third Person, Plural, Perfect, Indicative',
    'v3pria---': 'Verb, Third Person, Plural, Perfect, Indicative, Active',
    'v3prie---': 'Verb, Third Person, Plural, Perfect, Indicative, Medio-Passive',
    'v3prsa---': 'Verb, Third Person, Plural, Perfect, Subjunctive, Active',
    'v3sai----': 'Verb, Third Person, Singular, Aorist, Indicative',
    'v3saia---': 'Verb, Third Person, Singular, Aorist, Indicative, Active',
    'v3said---': 'Verb, Third Person, Singular, Aorist, Indicative, Voice=d',
    'v3saie---': 'Verb, Third Person, Singular, Aorist, Indicative, Medio-Passive',
    'v3saim---': 'Verb, Third Person, Singular, Aorist, Indicative, Middle',
    'v3saip---': 'Verb, Third Person, Singular, Aorist, Indicative, Passive',
    'v3sama---': 'Verb, Third Person, Singular, Aorist, Imperative, Active',
    'v3samm---': 'Verb, Third Person, Singular, Aorist, Imperative, Middle',
    'v3samp---': 'Verb, Third Person, Singular, Aorist, Imperative, Passive',
    'v3sana---': 'Verb, Third Person, Singular, Aorist, Infinitive, Active',
    'v3sao----': 'Verb, Third Person, Singular, Aorist, Optative',
    'v3saoa---': 'Verb, Third Person, Singular, Aorist, Optative, Active',
    'v3saoe---': 'Verb, Third Person, Singular, Aorist, Optative, Medio-Passive',
    'v3saom---': 'Verb, Third Person, Singular, Aorist, Optative, Middle',
    'v3saop---': 'Verb, Third Person, Singular, Aorist, Optative, Passive',
    'v3sas----': 'Verb, Third Person, Singular, Aorist, Subjunctive',
    'v3sasa---': 'Verb, Third Person, Singular, Aorist, Subjunctive, Active',
    'v3sase---': 'Verb, Third Person, Singular, Aorist, Subjunctive, Medio-Passive',
    'v3sasm---': 'Verb, Third Person, Singular, Aorist, Subjunctive, Middle',
    'v3sasp---': 'Verb, Third Person, Singular, Aorist, Subjunctive, Passive',
    'v3sfi----': 'Verb, Third Person, Singular, Future, Indicative',
    'v3sfia---': 'Verb, Third Person, Singular, Future, Indicative, Active',
    'v3sfim---': 'Verb, Third Person, Singular, Future, Indicative, Middle',
    'v3sfip---': 'Verb, Third Person, Singular, Future, Indicative, Passive',
    'v3sfoa---': 'Verb, Third Person, Singular, Future, Optative, Active',
    'v3sfom---': 'Verb, Third Person, Singular, Future, Optative, Middle',
    'v3sii----': 'Verb, Third Person, Singular, Imperfect, Indicative',
    'v3siia---': 'Verb, Third Person, Singular, Imperfect, Indicative, Active',
    'v3siie---': 'Verb, Third Person, Singular, Imperfect, Indicative, Medio-Passive',
    'v3siip---': 'Verb, Third Person, Singular, Imperfect, Indicative, Passive',
    'v3sli----': 'Verb, Third Person, Singular, Plusquamperfect, Indicative',
    'v3slia---': 'Verb, Third Person, Singular, Plusquamperfect, Indicative, Active',
    'v3slie---': 'Verb, Third Person, Singular, Plusquamperfect, Indicative, Medio-Passive',
    'v3slim---': 'Verb, Third Person, Singular, Plusquamperfect, Indicative, Middle',
    'v3slip---': 'Verb, Third Person, Singular, Plusquamperfect, Indicative, Passive',
    'v3spi----': 'Verb, Third Person, Singular, Present, Indicative',
    'v3spia---': 'Verb, Third Person, Singular, Present, Indicative, Active',
    'v3spie---': 'Verb, Third Person, Singular, Present, Indicative, Medio-Passive',
    'v3spip---': 'Verb, Third Person, Singular, Present, Indicative, Passive',
    'v3spm----': 'Verb, Third Person, Singular, Present, Imperative',
    'v3spma---': 'Verb, Third Person, Singular, Present, Imperative, Active',
    'v3spme---': 'Verb, Third Person, Singular, Present, Imperative, Medio-Passive',
    'v3spoa---': 'Verb, Third Person, Singular, Present, Optative, Active',
    'v3spoe---': 'Verb, Third Person, Singular, Present, Optative, Medio-Passive',
    'v3sps----': 'Verb, Third Person, Singular, Present, Subjunctive',
    'v3spsa---': 'Verb, Third Person, Singular, Present, Subjunctive, Active',
    'v3spse---': 'Verb, Third Person, Singular, Present, Subjunctive, Medio-Passive',
    'v3sri----': 'Verb, Third Person, Singular, Perfect, Indicative',
    'v3sria---': 'Verb, Third Person, Singular, Perfect, Indicative, Active',
    'v3srie---': 'Verb, Third Person, Singular, Perfect, Indicative, Medio-Passive',
    'v3srip---': 'Verb, Third Person, Singular, Perfect, Indicative, Passive',
    'v3srma---': 'Verb, Third Person, Singular, Perfect, Imperative, Active',
    'v3srme---': 'Verb, Third Person, Singular, Perfect, Imperative, Medio-Passive',
    'v3sroa---': 'Verb, Third Person, Singular, Perfect, Optative, Active',
    'v3srsa---': 'Verb, Third Person, Singular, Perfect, Subjunctive, Active',
    'v3stie---': 'Verb, Third Person, Singular, Future Perfect, Indicative, Medio-Passive',
    'v3stip---': 'Verb, Third Person, Singular, Future Perfect, Indicative, Passive',
    'x--------': 'Not Available (Elliptical Node)',
    'x-----n--': 'Not Available (Elliptical Node), Neuter',
    'x-s---na-': 'Not Available (Elliptical Node), Singular, Neuter, Accusative'
  };
  registryState._XPOS_BY_LANG.grc = ancientGreekState.XPOS_GRC;

  // ---------------------------------------------------------------------------
  // DEP — shared UD dependency relation hover text
  // ---------------------------------------------------------------------------
  return true;
}
