import { dependenciesState } from './dependencies.state.mjs';
export function initializeDependencies() {
  // ---------------------------------------------------------------------------
  // DEP — shared UD dependency relation hover text
  // ---------------------------------------------------------------------------

  dependenciesState.DEP = {
    acl: 'Noun Modifying Clause',
    'acl:attr': 'Noun Modifying Clause (Attributive)',
    'acl:cont': 'Noun Modifying Clause (Content)',
    'acl:crel': 'Noun Modifying Clause (Content-Relative)',
    'acl:dpct': 'Noun Modifying Clause (Depictive)',
    'acl:pred': 'Noun Modifying Clause (Predicative)',
    'acl:ptcp': 'Noun Modifying Clause (Participial)',
    'acl:rel': 'Noun Modifying Clause (Relative)',
    'acl:relc': 'Noun Modifying Clause (Relative-Clause)',
    'acl:relcl': 'Noun Modifying Clause (Relative-Clause)',
    advcl: 'Adverbial Clause',
    'advcl:abs': 'Adverbial Clause (Absolute)',
    'advcl:caus': 'Adverbial Clause (Causal)',
    'advcl:ccomp': 'Adverbial Clause (Complement-Like)',
    'advcl:cleft': 'Adverbial Clause (Cleft)',
    'advcl:cmp': 'Adverbial Clause (Comparative)',
    'advcl:concess': 'Adverbial Clause (Concessive)',
    'advcl:cond': 'Adverbial Clause (Conditional)',
    'advcl:consec': 'Adverbial Clause (Consecutive / Result)',
    'advcl:dpct': 'Adverbial Clause (Depictive)',
    'advcl:fin': 'Adverbial Clause (Finite)',
    'advcl:lcl': 'Adverbial Clause (Locative)',
    'advcl:manner': 'Adverbial Clause (Manner)',
    'advcl:pred': 'Adverbial Clause (Predicative)',
    'advcl:relcl': 'Adverbial Clause (Relative-Clause)',
    'advcl:temp': 'Adverbial Clause (Temporal)',
    'advcl:tcl': 'Adverbial Clause (Temporal)',
    advl: 'Adverbial Modifier',
    advmod: 'Adverbial Modifier',
    'advmod:df': 'Adverbial Modifier (Duration / Frequency)',
    'advmod:emph': 'Adverbial Modifier (Emphatic)',
    'advmod:lmod': 'Adverbial Modifier (Locative)',
    'advmod:neg': 'Adverbial Modifier (Negative)',
    'advmod:tmod': 'Adverbial Modifier (Temporal)',
    amod: 'Adjective Modifier',
    aposs: 'Appositional Possessive Modifier',
    appos: 'Apposition',
    aux: 'Auxiliary',
    'aux:caus': 'Auxiliary (Causal)',
    'aux:pass': 'Auxiliary (Passive)',
    'aux:q': 'Auxiliary (Question)',
    'aux:tense': 'Auxiliary (Tense)',
    case: 'Case Marker',
    'case:aspect': 'Case Marker (Aspect)',
    'case:dec': 'Case Marker (De-Particle)',
    'case:loc': 'Case Marker (Localizer / Postposition)',
    'case:pref': 'Case Marker (Prefixal)',
    'case:sim': 'Case Marker (Similative)',
    'case:suff': 'Case Marker (Suffixal)',
    'case:voc': 'Case Marker (Vocative)',
    cc: 'Coordinating Conjunction',
    'cc:appos': 'Coordinating Conjunction (Appositional)',
    'cc:preconj': 'Coordinating Conjunction (Preconjunct)',
    ccomp: 'Clausal Complement',
    'ccomp:rel': 'Clausal Complement (Relative)',
    'ccomp:relcl': 'Clausal Complement (Relative-Clause)',
    clf: 'Classifier',
    cnj: 'Conjunct',
    compound: 'Compound Part',
    'compound:affix': 'Compound Part (Affix)',
    'compound:coord': 'Compound Part (Coord)',
    'compound:dir': 'Compound Part (Directional)',
    'compound:ext': 'Compound Part (Extent / Result)',
    'compound:lvc': 'Compound Part (Light-Verb Construction)',
    'compound:name': 'Compound Part (Name)',
    'compound:plur': 'Compound Part (Plural)',
    'compound:prt': 'Compound Part (Particle)',
    'compound:redup': 'Compound Part (Reduplicated)',
    'compound:svc': 'Compound Part (Serial Verb)',
    'compound:vo': 'Compound Part (Verb-Object)',
    'compound:vv': 'Compound Part (Verb-Verb)',
    conj: 'Conjunct',
    'conj:expl': 'Conjunct (Expl)',
    'conj:temp': 'Conjunct (Temporal)',
    cop: 'Copula',
    csubj: 'Clausal Subject',
    'csubj:cleft': 'Clausal Subject (Cleft)',
    'csubj:cop': 'Clausal Subject (Cop)',
    'csubj:outer': 'Clausal Subject (Outer)',
    'csubj:pass': 'Clausal Subject (Passive)',
    'csubj:relcl': 'Clausal Subject (Relative-Clause)',
    ddet: 'Dependent Determiner',
    dep: 'Unspecified Dependent',
    'dep:der': 'Unspecified Dependent (Der)',
    det: 'Determiner',
    'det:numgov': 'Determiner (Number-Governing)',
    'det:nummod': 'Determiner (Number-Modifying)',
    'det:pos': 'Determiner (Possessive)',
    'det:poss': 'Determiner (Possessive)',
    'det:predet': 'Determiner (Predeterminer)',
    discourse: 'Discourse Particle',
    'discourse:emo': 'Discourse Particle (Emotive)',
    'discourse:q': 'Discourse Particle (Question)',
    'discourse:sp': 'Discourse Particle (Sentence-Final)',
    dislocated: 'Dislocated Element',
    'dislocated:csubj': 'Dislocated Element (Csubj)',
    'dislocated:nsubj': 'Dislocated Element (Nsubj)',
    'dislocated:obj': 'Dislocated Element (Obj)',
    'dislocated:obl': 'Dislocated Element (Obl)',
    'dislocated:vo': 'Dislocated Element (Verb-Object)',
    expl: 'Expletive',
    'expl:comp': 'Expletive (Complement)',
    'expl:impers': 'Expletive (Impersonal)',
    'expl:pass': 'Expletive (Passive)',
    'expl:pv': 'Expletive (Inherent Reflexive)',
    'expl:subj': 'Expletive (Subj)',
    fixed: 'Fixed Expression Part',
    flat: 'Flat Multiword Unit',
    'flat:foreign': 'Flat Multiword Unit (Foreign)',
    'flat:name': 'Flat Multiword Unit (Name)',
    'flat:vv': 'Flat Multiword Unit (Verb-Verb)',
    goeswith: 'Split Word Part',
    iobj: 'Indirect Object',
    'iobj:agent': 'Indirect Object (Agent)',
    list: 'List Item',
    mark: 'Clause Marker',
    'mark:adv': 'Clause Marker (Adverbial)',
    'mark:advb': 'Clause Marker (Adverbial)',
    'mark:comp': 'Clause Marker (Complement)',
    'mark:prt': 'Clause Marker (Particle)',
    'mark:rel': 'Clause Marker (Relative)',
    'mark:relcl': 'Clause Marker (Relative-Clause)',
    'mark:sim': 'Clause Marker (Similative)',
    marker: 'Marker',
    nmod: 'Nominal Modifier',
    'nmod:appos': 'Nominal Modifier (Appositional)',
    'nmod:cmp': 'Nominal Modifier (Comparative)',
    'nmod:npmod': 'Nominal Modifier (Noun-Phrase)',
    'nmod:part': 'Nominal Modifier (Partitive)',
    'nmod:poss': 'Nominal Modifier (Possessive)',
    'nmod:pred': 'Nominal Modifier (Predicative)',
    'nmod:temp': 'Nominal Modifier (Temporal)',
    'nmod:tmod': 'Nominal Modifier (Temporal)',
    'nmod:unmarked': 'Nominal Modifier (Unmarked)',
    nsubj: 'Nominal Subject',
    'nsubj:caus': 'Nominal Subject (Causal)',
    'nsubj:nc': 'Nominal Subject (Non-Canonical)',
    'nsubj:outer': 'Nominal Subject (Outer)',
    'nsubj:own': 'Nominal Subject (Owner)',
    'nsubj:pass': 'Nominal Subject (Passive)',
    nsuj: 'Subject',
    nummod: 'Numeral Modifier',
    'nummod:entity': 'Numeral Modifier (Entity)',
    'nummod:gov': 'Numeral Modifier (Governing)',
    obj: 'Object',
    'obj:agent': 'Object (Agent)',
    'obj:lvc': 'Object (Light-Verb Construction)',
    'obj:periph': 'Object (Peripheral)',
    obl: 'Oblique Nominal',
    'obl:agenet': 'Oblique Nominal (Agent)',
    'obl:agent': 'Oblique Nominal (Agent)',
    'obl:arg': 'Oblique Nominal (Argument)',
    'obl:benef': 'Oblique Nominal (Benefactive)',
    'obl:cau': 'Oblique Nominal (Causal)',
    'obl:goal': 'Oblique Nominal (Goal)',
    'obl:grad': 'Oblique Nominal (Degree)',
    'obl:instr': 'Oblique Nominal (Instrumental)',
    'obl:loc': 'Oblique Nominal (Locative)',
    'obl:lmod': 'Oblique Nominal (Locative)',
    'obl:manner': 'Oblique Nominal (Manner)',
    'obl:mmod': 'Oblique Nominal (Measure)',
    'obl:mod': 'Oblique Nominal (Modifier)',
    'obl:org': 'Oblique Nominal (Origin)',
    'obl:path': 'Oblique Nominal (Path)',
    'obl:patient': 'Oblique Nominal (Patient)',
    'obl:prep': 'Oblique Nominal (Prepositional)',
    'obl:soc': 'Oblique Nominal (Sociative)',
    'obl:source': 'Oblique Nominal (Source)',
    'obl:temp': 'Oblique Nominal (Temporal)',
    'obl:tlmod': 'Oblique Nominal (Time / Length)',
    'obl:tmod': 'Oblique Nominal (Temporal)',
    'obl:unmarked': 'Oblique Nominal (Unmarked)',
    orphan: 'Orphan',
    'orphan:appos': 'Orphan (Appositional)',
    'orphan:missing': 'Orphan (Missing Head)',
    'orphan:temp': 'Orphan (Temporal)',
    parataxis: 'Parataxis',
    'parataxis:appos': 'Parataxis (Appositional)',
    'parataxis:discourse': 'Parataxis (Discourse)',
    'parataxis:hashtag': 'Parataxis (Hashtag)',
    'parataxis:insert': 'Parataxis (Inserted)',
    'parataxis:nsubj': 'Parataxis (Nsubj)',
    'parataxis:obj': 'Parataxis (Obj)',
    'parataxis:rel': 'Parataxis (Relative)',
    punct: 'Punctuation',
    reparandum: 'Speech Repair',
    root: 'Root',
    senconj: 'Sentence Conjunct',
    subj: 'Subject',
    vocative: 'Direct Address',
    'vocative:mention': 'Direct Address (User Mention)',
    xcomp: 'Open Clausal Complement',
    'xcomp:pred': 'Open Clausal Complement (Predicative)',
    'xcomp:result': 'Open Clausal Complement (Resultative)'
  };

  // ---------------------------------------------------------------------------
  // FEATS — shared UD morphological feature hover text
  // ---------------------------------------------------------------------------
  return true;
}
