import { eastAsianState } from './east-asian.state.mjs';
export function initializeEastAsian() {
  eastAsianState.root = window;
  // ---------------------------------------------------------------------------
  // XPOS — language-specific fine-grained POS tags
  // ---------------------------------------------------------------------------

  eastAsianState.XPOS_ZH = {
    ADD: 'Unclear / Rare Miscellaneous Tag',
    AS: 'Aspect Marker Particle',
    BB: 'Disposal / Passive Marker',
    CC: 'Coordinating Conjunction',
    CD: 'Numeral / Number',
    DEC: 'Attributive Particle',
    DEV: 'Adverbial Particle',
    DT: 'Determiner',
    EC: 'List-Separator Punctuation',
    FW: 'Foreign Word',
    HYPH: 'Hyphen / Dash',
    IN: 'Preposition / Subordinator',
    JJ: 'Adjective',
    MD: 'Modal Auxiliary',
    NN: 'Common Noun',
    NNB: 'Unit / Measure / Classifier Noun',
    NNP: 'Proper Noun',
    PFA: 'Prefix',
    PRD: 'Demonstrative / Reflexive Pronoun',
    PRP: 'Personal Pronoun',
    RB: 'Adverb',
    SFA: 'Adjective-Forming Suffix',
    SFN: 'Noun-Forming Suffix',
    SFV: 'Verb-Forming Suffix',
    UH: 'Particle / Interjection',
    VC: 'Copula Verb',
    VV: 'Lexical Verb',
    WP: 'Relative / Interrogative Word'
  };
  eastAsianState.XPOS_JA = {
    NN: 'Common Noun / General Lexical Noun',
    NNP: 'Proper Noun / Named Entity',
    CD: 'Numeral / Numeric Token',
    NP: 'Pronoun / Pronominal Demonstrative',
    VV: 'Main Lexical Verb (Content Verb)',
    AV: 'Inflectional Auxiliary Verb Fragment',
    XV: 'Verbalizer / Derivational Verb Fragment',
    XA: 'Existential Or Support Verb',
    JJ: 'Inflecting Adjective Form',
    JN: 'Adjectival Noun Stem / Nominal Modifier',
    JR: 'Prenominal Determiner / Attributive Determiner',
    RB: 'Adverb',
    CC: 'Conjunction / Discourse Connective',
    UH: 'Interjection',
    PS: 'Simple Case Particle / Postposition',
    PK: 'Topic, Focus, Or Contrast Particle',
    PC: 'Clause-Linking Or Subordinating Particle',
    PA: 'Adverbial, Degree, Or Limiting Particle',
    PNB: 'Nominalizer (Clause-To-Noun Marker)',
    PE: 'Sentence-Final Particle (Non-Question)',
    PM: 'Core Genitive Linker Particle',
    PQ: 'Quotative Marker / Complementizer',
    PH: 'Listing Or Coordination Marker',
    PP: 'Compound Postposition',
    PN: 'Possessive Or Genitive Bound Form',
    PF: 'Sentence-Final Question Marker',
    XP: 'Bound Prefix Element',
    XS: 'Bound Suffix Element',
    XSC: 'Counter, Unit, Or Classifier Suffix',
    XPC: 'Number Or Date Modifier / Numeric Connector Element',
    PX: 'Fixed Postposition-Like Expression Or Adpositional Chunk',
    SYM: 'Symbol, Punctuation, Or Non-Lexical Mark',
    UNK: 'Unknown, Residual, Or Out-Of-Vocabulary Token',
    _: 'Null Or Placeholder',
    AJ: 'Dependent Adjectival Element',
    AJN: 'Adjectival-Noun Suffix',
    NR: 'Temporal Or Sequence Noun Used Adverbially',
    NB: 'Bound Or Formal Noun'
  };
  eastAsianState.XPOS_KO = {
    NCN: 'Common Noun',
    NCPA: 'Action Noun',
    NCPS: 'State Noun',
    NBN: 'Bound (Dependent) Noun',
    NBU: 'Unit / Counter Noun',
    NNC: 'Cardinal Number',
    NNO: 'Native / Ordinal Number',
    NPD: 'Demonstrative Pronoun',
    NPP: 'Personal Pronoun',
    NQ: 'Proper Noun',
    PVG: 'Verb',
    PVD: 'Verb (Variant / Defective)',
    PAA: 'Descriptive Verb (Adjective)',
    PAD: 'Adnominal Adjective',
    PX: 'Auxiliary Predicate',
    XP: 'Bound Prefix Element',
    ECC: 'Coordinating Connective Ending',
    ECS: 'Subordinating Connective Ending',
    ECX: 'Auxiliary Connective Ending',
    EF: 'Sentence-Final Ending',
    EP: 'Pre-Final Ending (Tense / Honorific)',
    ETM: 'Adnominalizing Ending',
    ETN: 'Nominalizing Ending',
    JCA: 'Adverbial Case Particle',
    JCC: 'Complement Case Particle',
    JCJ: 'Conjunctive Particle',
    JCM: 'Adnominal Case Particle (Genitive)',
    JCO: 'Object Case Particle',
    JCR: 'Quotative Case Particle',
    JCS: 'Subject Case Particle',
    JCT: 'Locative / Directional Particle',
    JP: 'Copula',
    JCV: 'Vocative Case Particle',
    JXC: 'Delimiter Particle',
    JXF: 'Focus / Special Particle',
    JXT: 'Topic Particle',
    MAD: 'Demonstrative Adverb',
    MAG: 'General Adverb',
    MAJ: 'Conjunctive Adverb',
    MMA: 'Attributive Determiner',
    MMD: 'Demonstrative Determiner',
    XSA: 'Adjective-Deriving Suffix',
    XSM: 'Adverb-Deriving Suffix',
    XSN: 'Noun-Deriving Suffix',
    XSV: 'Verb-Deriving Suffix',
    SF: 'Sentence-Final Punctuation',
    SL: 'Left Bracket / Parenthesis',
    SP: 'Comma / Separator',
    SR: 'Right Bracket / Parenthesis',
    SU: 'Symbol / Unknown Punctuation',
    II: 'Interjection',
    F: 'Foreign Word',
    _: 'Null / No Tag Assigned'
  };
  eastAsianState.XPOS_LZH = {
    'n,名詞,不可譲,属性': 'Noun: Inalienable Attribute',
    'n,名詞,不可譲,疾病': 'Noun: Inalienable / Disease',
    'n,名詞,不可譲,身体': 'Noun: Inalienable / Body Part',
    'n,名詞,主体,動物': 'Noun: Entity / Animal',
    'n,名詞,主体,国名': 'Noun: Entity / Country Name',
    'n,名詞,主体,書物': 'Noun: Entity / Book Or Text',
    'n,名詞,主体,機関': 'Noun: Entity / Institution',
    'n,名詞,主体,集団': 'Noun: Entity / Group Or Collective',
    'n,名詞,人,その他の人名': 'Noun: Person / Other Personal Name',
    'n,名詞,人,人': 'Noun: Person (General)',
    'n,名詞,人,名': 'Noun: Person / Given Name',
    'n,名詞,人,姓氏': 'Noun: Person / Surname',
    'n,名詞,人,役割': 'Noun: Person / Role Or Title',
    'n,名詞,人,複合的人名': 'Noun: Person / Compound Name',
    'n,名詞,人,関係': 'Noun: Person / Relationship',
    'n,名詞,制度,儀礼': 'Noun: Institution / Ritual Or Ceremony',
    'n,名詞,制度,場': 'Noun: Institution / Place Or Venue',
    'n,名詞,可搬,乗り物': 'Noun: Portable / Vehicle',
    'n,名詞,可搬,伝達': 'Noun: Portable / Communication Tool',
    'n,名詞,可搬,成果物': 'Noun: Portable / Product Or Artifact',
    'n,名詞,可搬,糧食': 'Noun: Portable / Food Or Provisions',
    'n,名詞,可搬,道具': 'Noun: Portable / Tool Or Implement',
    'n,名詞,固定物,地名': 'Noun: Fixed / Place Name',
    'n,名詞,固定物,地形': 'Noun: Fixed / Terrain Or Landform',
    'n,名詞,固定物,建造物': 'Noun: Fixed / Building Or Structure',
    'n,名詞,固定物,樹木': 'Noun: Fixed / Tree Or Plant',
    'n,名詞,固定物,関係': 'Noun: Fixed / Spatial Relation',
    'n,名詞,天象,天文': 'Noun: Celestial / Astronomy',
    'n,名詞,天象,怪異': 'Noun: Celestial / Omen Or Anomaly',
    'n,名詞,天象,気象': 'Noun: Celestial / Weather',
    'n,名詞,度量衡,*': 'Noun: Measurement Or Unit',
    'n,名詞,思考,*': 'Noun: Thought Or Concept',
    'n,名詞,描写,形質': 'Noun: Description / Quality Or Form',
    'n,名詞,描写,態度': 'Noun: Description / Attitude',
    'n,名詞,数量,*': 'Noun: Quantity',
    'n,名詞,時,*': 'Noun: Time Or Temporal',
    'n,名詞,行為,*': 'Noun: Action Or Conduct',
    'n,代名詞,人称,他': 'Pronoun: Third Person',
    'n,代名詞,人称,止格': 'Pronoun: Objective Case',
    'n,代名詞,人称,起格': 'Pronoun: Nominative Case',
    'n,代名詞,指示,*': 'Pronoun: Demonstrative',
    'n,代名詞,疑問,*': 'Pronoun: Interrogative',
    'n,数詞,数,*': 'Numeral (Number Word)',
    'n,数詞,数字,*': 'Numeral (Digit)',
    'p,助詞,句末,*': 'Particle: Sentence-Final',
    'p,助詞,句頭,*': 'Particle: Sentence-Initial',
    'p,助詞,接続,並列': 'Particle: Conjunctive / Coordinate',
    'p,助詞,接続,体言化': 'Particle: Conjunctive / Nominalizer',
    'p,助詞,接続,属格': 'Particle: Conjunctive / Genitive',
    'p,助詞,提示,*': 'Particle: Topic Or Focus Marker',
    'p,感嘆詞,*,*': 'Interjection',
    'p,接尾辞,*,*': 'Suffix',
    's,記号,一般,*': 'Symbol (General)',
    'v,前置詞,基盤,*': 'Preposition: Basis Or Foundation',
    'v,前置詞,源泉,*': 'Preposition: Source Or Origin',
    'v,前置詞,経由,*': 'Preposition: Via Or Through',
    'v,前置詞,関係,*': 'Preposition: Relation',
    'v,副詞,判断,推定': 'Adverb: Judgment / Presumption',
    'v,副詞,判断,確定': 'Adverb: Judgment / Certainty',
    'v,副詞,判断,逆接': 'Adverb: Judgment / Concessive',
    'v,副詞,否定,体言否定': 'Adverb: Negation / Nominal Negation',
    'v,副詞,否定,有界': 'Adverb: Negation / Bounded',
    'v,副詞,否定,無界': 'Adverb: Negation / Unbounded',
    'v,副詞,否定,禁止': 'Adverb: Negation / Prohibitive',
    'v,副詞,描写,*': 'Adverb: Descriptive / Manner',
    'v,副詞,時相,変化': 'Adverb: Aspect / Change',
    'v,副詞,時相,完了': 'Adverb: Aspect / Completion',
    'v,副詞,時相,将来': 'Adverb: Aspect / Future',
    'v,副詞,時相,恒常': 'Adverb: Aspect / Habitual',
    'v,副詞,時相,現在': 'Adverb: Aspect / Present',
    'v,副詞,時相,終局': 'Adverb: Aspect / Finality',
    'v,副詞,時相,緊接': 'Adverb: Aspect / Immediate Succession',
    'v,副詞,時相,過去': 'Adverb: Aspect / Past',
    'v,副詞,疑問,原因': 'Adverb: Interrogative / Reason',
    'v,副詞,疑問,反語': 'Adverb: Interrogative / Rhetorical',
    'v,副詞,疑問,所在': 'Adverb: Interrogative / Location',
    'v,副詞,程度,やや高度': 'Adverb: Degree / Moderately High',
    'v,副詞,程度,極度': 'Adverb: Degree / Extreme',
    'v,副詞,範囲,共同': 'Adverb: Scope / Collective',
    'v,副詞,範囲,総括': 'Adverb: Scope / Comprehensive',
    'v,副詞,範囲,限定': 'Adverb: Scope / Restrictive',
    'v,副詞,頻度,偶発': 'Adverb: Frequency / Occasional',
    'v,副詞,頻度,重複': 'Adverb: Frequency / Repeated',
    'v,副詞,頻度,頻繁': 'Adverb: Frequency / Frequent',
    'v,助動詞,受動,*': 'Auxiliary Verb: Passive',
    'v,助動詞,可能,*': 'Auxiliary Verb: Potential Or Ability',
    'v,助動詞,必要,*': 'Auxiliary Verb: Necessity',
    'v,助動詞,願望,*': 'Auxiliary Verb: Wish Or Desire',
    'v,動詞,変化,制度': 'Verb: Change / Institutional',
    'v,動詞,変化,性質': 'Verb: Change / Quality Or Nature',
    'v,動詞,変化,生物': 'Verb: Change / Biological',
    'v,動詞,存在,存在': 'Verb: Existence',
    'v,動詞,描写,境遇': 'Verb: Description / Circumstance',
    'v,動詞,描写,形質': 'Verb: Description / Form Or Quality',
    'v,動詞,描写,態度': 'Verb: Description / Attitude',
    'v,動詞,描写,量': 'Verb: Description / Quantity',
    'v,動詞,行為,交流': 'Verb: Action / Exchange Or Interaction',
    'v,動詞,行為,伝達': 'Verb: Action / Communication',
    'v,動詞,行為,使役': 'Verb: Action / Causative',
    'v,動詞,行為,儀礼': 'Verb: Action / Ritual Or Ceremony',
    'v,動詞,行為,分類': 'Verb: Action / Classification',
    'v,動詞,行為,動作': 'Verb: Action / Motion',
    'v,動詞,行為,姿勢': 'Verb: Action / Posture',
    'v,動詞,行為,役割': 'Verb: Action / Role Or Function',
    'v,動詞,行為,得失': 'Verb: Action / Gain Or Loss',
    'v,動詞,行為,態度': 'Verb: Action / Attitude Or Manner',
    'v,動詞,行為,生産': 'Verb: Action / Production',
    'v,動詞,行為,移動': 'Verb: Action / Movement',
    'v,動詞,行為,設置': 'Verb: Action / Establishment',
    'v,動詞,行為,飲食': 'Verb: Action / Eating And Drinking',
    _: 'Null / No Tag Assigned'
  };
  return true;
}
