import { latinState } from './latin.state.mjs';
export function initializeLatin() {
  latinState.XPOS_LATIN = {
    'Propn|n|-|p|-|-|-|f|a|-': 'Proper Noun, Plural, Feminine, Accusative',
    'Propn|n|-|p|-|-|-|f|b|-': 'Proper Noun, Plural, Feminine, Ablative',
    'Propn|n|-|p|-|-|-|f|n|-': 'Proper Noun, Plural, Feminine, Nominative',
    'Propn|n|-|p|-|-|-|m|b|-': 'Proper Noun, Plural, Masculine, Ablative',
    'Propn|n|-|p|-|-|-|m|g|-': 'Proper Noun, Plural, Masculine, Genitive',
    'Propn|n|-|p|-|-|-|m|n|-': 'Proper Noun, Plural, Masculine, Nominative',
    'Propn|n|-|p|-|-|-|n|a|-': 'Proper Noun, Plural, Neuter, Accusative',
    'Propn|n|-|p|-|-|-|n|b|-': 'Proper Noun, Plural, Neuter, Ablative',
    'Propn|n|-|p|-|-|-|n|n|-': 'Proper Noun, Plural, Neuter, Nominative',
    'Propn|n|-|s|-|-|-|f|a|-': 'Proper Noun, Singular, Feminine, Accusative',
    'Propn|n|-|s|-|-|-|f|b|-': 'Proper Noun, Singular, Feminine, Ablative',
    'Propn|n|-|s|-|-|-|f|d|-': 'Proper Noun, Singular, Feminine, Dative',
    'Propn|n|-|s|-|-|-|f|g|-': 'Proper Noun, Singular, Feminine, Genitive',
    'Propn|n|-|s|-|-|-|f|l|-': 'Proper Noun, Singular, Feminine, Locative',
    'Propn|n|-|s|-|-|-|f|n|-': 'Proper Noun, Singular, Feminine, Nominative',
    'Propn|n|-|s|-|-|-|m|a|-': 'Proper Noun, Singular, Masculine, Accusative',
    'Propn|n|-|s|-|-|-|m|b|-': 'Proper Noun, Singular, Masculine, Ablative',
    'Propn|n|-|s|-|-|-|m|d|-': 'Proper Noun, Singular, Masculine, Dative',
    'Propn|n|-|s|-|-|-|m|g|-': 'Proper Noun, Singular, Masculine, Genitive',
    'Propn|n|-|s|-|-|-|m|n|-': 'Proper Noun, Singular, Masculine, Nominative',
    'Propn|n|-|s|-|-|-|m|v|-': 'Proper Noun, Singular, Masculine, Vocative',
    'Propn|n|-|s|-|-|-|n|a|-': 'Proper Noun, Singular, Neuter, Accusative',
    'Propn|n|-|s|-|-|-|n|b|-': 'Proper Noun, Singular, Neuter, Ablative',
    'Propn|n|-|s|-|-|-|n|d|-': 'Proper Noun, Singular, Neuter, Dative',
    'Propn|n|-|s|-|-|-|n|g|-': 'Proper Noun, Singular, Neuter, Genitive',
    'Propn|n|-|s|-|-|-|n|n|-': 'Proper Noun, Singular, Neuter, Nominative',
    Punc: 'Punctuation',
    SYM: 'Symbol',
    'a|a|-|-|-|-|-|-|-|-': 'Adjective',
    'a|a|-|p|-|-|-|f|a|-': 'Adjective, Plural, Feminine, Accusative',
    'a|a|-|p|-|-|-|f|b|-': 'Adjective, Plural, Feminine, Ablative',
    'a|a|-|p|-|-|-|f|d|-': 'Adjective, Plural, Feminine, Dative',
    'a|a|-|p|-|-|-|f|n|-': 'Adjective, Plural, Feminine, Nominative',
    'a|a|-|p|-|-|-|f|n|c': 'Adjective, Plural, Feminine, Nominative, Comparative',
    'a|a|-|p|-|-|-|f|n|s': 'Adjective, Plural, Feminine, Nominative, Superlative',
    'a|a|-|p|-|-|-|m|a|-': 'Adjective, Plural, Masculine, Accusative',
    'a|a|-|p|-|-|-|m|a|c': 'Adjective, Plural, Masculine, Accusative, Comparative',
    'a|a|-|p|-|-|-|m|b|-': 'Adjective, Plural, Masculine, Ablative',
    'a|a|-|p|-|-|-|m|b|s': 'Adjective, Plural, Masculine, Ablative, Superlative',
    'a|a|-|p|-|-|-|m|d|-': 'Adjective, Plural, Masculine, Dative',
    'a|a|-|p|-|-|-|m|g|-': 'Adjective, Plural, Masculine, Genitive',
    'a|a|-|p|-|-|-|m|g|s': 'Adjective, Plural, Masculine, Genitive, Superlative',
    'a|a|-|p|-|-|-|m|n|-': 'Adjective, Plural, Masculine, Nominative',
    'a|a|-|p|-|-|-|m|n|c': 'Adjective, Plural, Masculine, Nominative, Comparative',
    'a|a|-|p|-|-|-|n|a|-': 'Adjective, Plural, Neuter, Accusative',
    'a|a|-|p|-|-|-|n|a|c': 'Adjective, Plural, Neuter, Accusative, Comparative',
    'a|a|-|p|-|-|-|n|b|-': 'Adjective, Plural, Neuter, Ablative',
    'a|a|-|p|-|-|-|n|d|-': 'Adjective, Plural, Neuter, Dative',
    'a|a|-|p|-|-|-|n|g|-': 'Adjective, Plural, Neuter, Genitive',
    'a|a|-|p|-|-|-|n|n|-': 'Adjective, Plural, Neuter, Nominative',
    'a|a|-|s|-|-|-|f|a|-': 'Adjective, Singular, Feminine, Accusative',
    'a|a|-|s|-|-|-|f|a|c': 'Adjective, Singular, Feminine, Accusative, Comparative',
    'a|a|-|s|-|-|-|f|b|-': 'Adjective, Singular, Feminine, Ablative',
    'a|a|-|s|-|-|-|f|b|c': 'Adjective, Singular, Feminine, Ablative, Comparative',
    'a|a|-|s|-|-|-|f|b|s': 'Adjective, Singular, Feminine, Ablative, Superlative',
    'a|a|-|s|-|-|-|f|d|-': 'Adjective, Singular, Feminine, Dative',
    'a|a|-|s|-|-|-|f|g|-': 'Adjective, Singular, Feminine, Genitive',
    'a|a|-|s|-|-|-|f|g|s': 'Adjective, Singular, Feminine, Genitive, Superlative',
    'a|a|-|s|-|-|-|f|n|-': 'Adjective, Singular, Feminine, Nominative',
    'a|a|-|s|-|-|-|m|a|-': 'Adjective, Singular, Masculine, Accusative',
    'a|a|-|s|-|-|-|m|a|c': 'Adjective, Singular, Masculine, Accusative, Comparative',
    'a|a|-|s|-|-|-|m|a|s': 'Adjective, Singular, Masculine, Accusative, Superlative',
    'a|a|-|s|-|-|-|m|b|-': 'Adjective, Singular, Masculine, Ablative',
    'a|a|-|s|-|-|-|m|b|c': 'Adjective, Singular, Masculine, Ablative, Comparative',
    'a|a|-|s|-|-|-|m|b|s': 'Adjective, Singular, Masculine, Ablative, Superlative',
    'a|a|-|s|-|-|-|m|d|-': 'Adjective, Singular, Masculine, Dative',
    'a|a|-|s|-|-|-|m|d|s': 'Adjective, Singular, Masculine, Dative, Superlative',
    'a|a|-|s|-|-|-|m|g|-': 'Adjective, Singular, Masculine, Genitive',
    'a|a|-|s|-|-|-|m|g|s': 'Adjective, Singular, Masculine, Genitive, Superlative',
    'a|a|-|s|-|-|-|m|n|-': 'Adjective, Singular, Masculine, Nominative',
    'a|a|-|s|-|-|-|m|n|s': 'Adjective, Singular, Masculine, Nominative, Superlative',
    'a|a|-|s|-|-|-|m|v|s': 'Adjective, Singular, Masculine, Vocative, Superlative',
    'a|a|-|s|-|-|-|n|a|-': 'Adjective, Singular, Neuter, Accusative',
    'a|a|-|s|-|-|-|n|a|c': 'Adjective, Singular, Neuter, Accusative, Comparative',
    'a|a|-|s|-|-|-|n|a|s': 'Adjective, Singular, Neuter, Accusative, Superlative',
    'a|a|-|s|-|-|-|n|b|-': 'Adjective, Singular, Neuter, Ablative',
    'a|a|-|s|-|-|-|n|b|c': 'Adjective, Singular, Neuter, Ablative, Comparative',
    'a|a|-|s|-|-|-|n|b|s': 'Adjective, Singular, Neuter, Ablative, Superlative',
    'a|a|-|s|-|-|-|n|d|-': 'Adjective, Singular, Neuter, Dative',
    'a|a|-|s|-|-|-|n|g|-': 'Adjective, Singular, Neuter, Genitive',
    'a|a|-|s|-|-|-|n|n|-': 'Adjective, Singular, Neuter, Nominative',
    'a|a|-|s|-|-|-|n|n|c': 'Adjective, Singular, Neuter, Nominative, Comparative',
    'a|a|1|p|-|-|-|f|a|-': 'Adjective, 1st Person, Plural, Feminine, Accusative',
    'a|a|1|p|-|-|-|f|b|-': 'Adjective, 1st Person, Plural, Feminine, Ablative',
    'a|a|1|p|-|-|-|f|g|-': 'Adjective, 1st Person, Plural, Feminine, Genitive',
    'a|a|1|p|-|-|-|f|n|-': 'Adjective, 1st Person, Plural, Feminine, Nominative',
    'a|a|1|p|-|-|-|m|a|-': 'Adjective, 1st Person, Plural, Masculine, Accusative',
    'a|a|1|p|-|-|-|m|b|-': 'Adjective, 1st Person, Plural, Masculine, Ablative',
    'a|a|1|p|-|-|-|m|d|-': 'Adjective, 1st Person, Plural, Masculine, Dative',
    'a|a|1|p|-|-|-|m|g|-': 'Adjective, 1st Person, Plural, Masculine, Genitive',
    'a|a|1|p|-|-|-|m|n|-': 'Adjective, 1st Person, Plural, Masculine, Nominative',
    'a|a|1|p|-|-|-|n|a|-': 'Adjective, 1st Person, Plural, Neuter, Accusative',
    'a|a|1|p|-|-|-|n|b|-': 'Adjective, 1st Person, Plural, Neuter, Ablative',
    'a|a|1|p|-|-|-|n|n|-': 'Adjective, 1st Person, Plural, Neuter, Nominative',
    'a|a|1|s|-|-|-|f|a|-': 'Adjective, 1st Person, Singular, Feminine, Accusative',
    'a|a|1|s|-|-|-|f|b|-': 'Adjective, 1st Person, Singular, Feminine, Ablative',
    'a|a|1|s|-|-|-|f|d|-': 'Adjective, 1st Person, Singular, Feminine, Dative',
    'a|a|1|s|-|-|-|f|g|-': 'Adjective, 1st Person, Singular, Feminine, Genitive',
    'a|a|1|s|-|-|-|f|n|-': 'Adjective, 1st Person, Singular, Feminine, Nominative',
    'a|a|1|s|-|-|-|m|a|-': 'Adjective, 1st Person, Singular, Masculine, Accusative',
    'a|a|1|s|-|-|-|m|b|-': 'Adjective, 1st Person, Singular, Masculine, Ablative',
    'a|a|1|s|-|-|-|m|d|-': 'Adjective, 1st Person, Singular, Masculine, Dative',
    'a|a|1|s|-|-|-|m|g|-': 'Adjective, 1st Person, Singular, Masculine, Genitive',
    'a|a|1|s|-|-|-|m|n|-': 'Adjective, 1st Person, Singular, Masculine, Nominative',
    'a|a|1|s|-|-|-|n|a|-': 'Adjective, 1st Person, Singular, Neuter, Accusative',
    'a|a|1|s|-|-|-|n|b|-': 'Adjective, 1st Person, Singular, Neuter, Ablative',
    'a|a|1|s|-|-|-|n|g|-': 'Adjective, 1st Person, Singular, Neuter, Genitive',
    'a|a|1|s|-|-|-|n|n|-': 'Adjective, 1st Person, Singular, Neuter, Nominative',
    'a|a|2|p|-|-|-|f|a|-': 'Adjective, 2nd Person, Plural, Feminine, Accusative',
    'a|a|2|p|-|-|-|f|b|-': 'Adjective, 2nd Person, Plural, Feminine, Ablative',
    'a|a|2|p|-|-|-|f|n|-': 'Adjective, 2nd Person, Plural, Feminine, Nominative',
    'a|a|2|p|-|-|-|m|a|-': 'Adjective, 2nd Person, Plural, Masculine, Accusative',
    'a|a|2|p|-|-|-|m|b|-': 'Adjective, 2nd Person, Plural, Masculine, Ablative',
    'a|a|2|p|-|-|-|m|d|-': 'Adjective, 2nd Person, Plural, Masculine, Dative',
    'a|a|2|p|-|-|-|m|g|-': 'Adjective, 2nd Person, Plural, Masculine, Genitive',
    'a|a|2|p|-|-|-|m|n|-': 'Adjective, 2nd Person, Plural, Masculine, Nominative',
    'a|a|2|p|-|-|-|n|a|-': 'Adjective, 2nd Person, Plural, Neuter, Accusative',
    'a|a|2|s|-|-|-|f|a|-': 'Adjective, 2nd Person, Singular, Feminine, Accusative',
    'a|a|2|s|-|-|-|f|b|-': 'Adjective, 2nd Person, Singular, Feminine, Ablative',
    'a|a|2|s|-|-|-|f|d|-': 'Adjective, 2nd Person, Singular, Feminine, Dative',
    'a|a|2|s|-|-|-|f|g|-': 'Adjective, 2nd Person, Singular, Feminine, Genitive',
    'a|a|2|s|-|-|-|f|n|-': 'Adjective, 2nd Person, Singular, Feminine, Nominative',
    'a|a|2|s|-|-|-|m|a|-': 'Adjective, 2nd Person, Singular, Masculine, Accusative',
    'a|a|2|s|-|-|-|m|b|-': 'Adjective, 2nd Person, Singular, Masculine, Ablative',
    'a|a|2|s|-|-|-|m|d|-': 'Adjective, 2nd Person, Singular, Masculine, Dative',
    'a|a|2|s|-|-|-|m|g|-': 'Adjective, 2nd Person, Singular, Masculine, Genitive',
    'a|a|2|s|-|-|-|m|n|-': 'Adjective, 2nd Person, Singular, Masculine, Nominative',
    'a|a|2|s|-|-|-|n|a|-': 'Adjective, 2nd Person, Singular, Neuter, Accusative',
    'a|a|2|s|-|-|-|n|b|-': 'Adjective, 2nd Person, Singular, Neuter, Ablative',
    'a|a|2|s|-|-|-|n|g|-': 'Adjective, 2nd Person, Singular, Neuter, Genitive',
    'a|a|3|p|-|-|-|f|a|-': 'Adjective, 3rd Person, Plural, Feminine, Accusative',
    'a|a|3|p|-|-|-|f|b|-': 'Adjective, 3rd Person, Plural, Feminine, Ablative',
    'a|a|3|p|-|-|-|f|n|-': 'Adjective, 3rd Person, Plural, Feminine, Nominative',
    'a|a|3|p|-|-|-|m|a|-': 'Adjective, 3rd Person, Plural, Masculine, Accusative',
    'a|a|3|p|-|-|-|m|b|-': 'Adjective, 3rd Person, Plural, Masculine, Ablative',
    'a|a|3|p|-|-|-|m|d|-': 'Adjective, 3rd Person, Plural, Masculine, Dative',
    'a|a|3|p|-|-|-|m|g|-': 'Adjective, 3rd Person, Plural, Masculine, Genitive',
    'a|a|3|p|-|-|-|n|a|-': 'Adjective, 3rd Person, Plural, Neuter, Accusative',
    'a|a|3|p|-|-|-|n|b|-': 'Adjective, 3rd Person, Plural, Neuter, Ablative',
    'a|a|3|s|-|-|-|f|a|-': 'Adjective, 3rd Person, Singular, Feminine, Accusative',
    'a|a|3|s|-|-|-|f|b|-': 'Adjective, 3rd Person, Singular, Feminine, Ablative',
    'a|a|3|s|-|-|-|f|d|-': 'Adjective, 3rd Person, Singular, Feminine, Dative',
    'a|a|3|s|-|-|-|f|g|-': 'Adjective, 3rd Person, Singular, Feminine, Genitive',
    'a|a|3|s|-|-|-|f|n|-': 'Adjective, 3rd Person, Singular, Feminine, Nominative',
    'a|a|3|s|-|-|-|m|a|-': 'Adjective, 3rd Person, Singular, Masculine, Accusative',
    'a|a|3|s|-|-|-|m|b|-': 'Adjective, 3rd Person, Singular, Masculine, Ablative',
    'a|a|3|s|-|-|-|m|g|-': 'Adjective, 3rd Person, Singular, Masculine, Genitive',
    'a|a|3|s|-|-|-|m|n|-': 'Adjective, 3rd Person, Singular, Masculine, Nominative',
    'a|a|3|s|-|-|-|n|a|-': 'Adjective, 3rd Person, Singular, Neuter, Accusative',
    'a|a|3|s|-|-|-|n|b|-': 'Adjective, 3rd Person, Singular, Neuter, Ablative',
    'c|c|-|-|-|-|-|-|-|-': 'Conjunction',
    'd|d|-|-|-|-|-|-|-|-': 'Adverb',
    'd|d|-|-|-|-|-|-|-|c': 'Adverb, Comparative',
    'd|d|-|-|-|-|-|-|-|s': 'Adverb, Superlative',
    'e|e|-|-|-|-|-|-|-|-': 'Exclamation',
    'm|m|-|-|-|-|-|-|-|-': 'Numeral',
    'n|n|-|p|-|-|-|f|a|-': 'Noun, Plural, Feminine, Accusative',
    'n|n|-|p|-|-|-|f|b|-': 'Noun, Plural, Feminine, Ablative',
    'n|n|-|p|-|-|-|f|d|-': 'Noun, Plural, Feminine, Dative',
    'n|n|-|p|-|-|-|f|g|-': 'Noun, Plural, Feminine, Genitive',
    'n|n|-|p|-|-|-|f|n|-': 'Noun, Plural, Feminine, Nominative',
    'n|n|-|p|-|-|-|m|a|-': 'Noun, Plural, Masculine, Accusative',
    'n|n|-|p|-|-|-|m|b|-': 'Noun, Plural, Masculine, Ablative',
    'n|n|-|p|-|-|-|m|d|-': 'Noun, Plural, Masculine, Dative',
    'n|n|-|p|-|-|-|m|g|-': 'Noun, Plural, Masculine, Genitive',
    'n|n|-|p|-|-|-|m|n|-': 'Noun, Plural, Masculine, Nominative',
    'n|n|-|p|-|-|-|n|a|-': 'Noun, Plural, Neuter, Accusative',
    'n|n|-|p|-|-|-|n|b|-': 'Noun, Plural, Neuter, Ablative',
    'n|n|-|p|-|-|-|n|g|-': 'Noun, Plural, Neuter, Genitive',
    'n|n|-|p|-|-|-|n|n|-': 'Noun, Plural, Neuter, Nominative',
    'n|n|-|s|-|-|-|f|a|-': 'Noun, Singular, Feminine, Accusative',
    'n|n|-|s|-|-|-|f|b|-': 'Noun, Singular, Feminine, Ablative',
    'n|n|-|s|-|-|-|f|d|-': 'Noun, Singular, Feminine, Dative',
    'n|n|-|s|-|-|-|f|g|-': 'Noun, Singular, Feminine, Genitive',
    'n|n|-|s|-|-|-|f|l|-': 'Noun, Singular, Feminine, Locative',
    'n|n|-|s|-|-|-|f|n|-': 'Noun, Singular, Feminine, Nominative',
    'n|n|-|s|-|-|-|m|a|-': 'Noun, Singular, Masculine, Accusative',
    'n|n|-|s|-|-|-|m|b|-': 'Noun, Singular, Masculine, Ablative',
    'n|n|-|s|-|-|-|m|d|-': 'Noun, Singular, Masculine, Dative',
    'n|n|-|s|-|-|-|m|g|-': 'Noun, Singular, Masculine, Genitive',
    'n|n|-|s|-|-|-|m|n|-': 'Noun, Singular, Masculine, Nominative',
    'n|n|-|s|-|-|-|m|v|-': 'Noun, Singular, Masculine, Vocative',
    'n|n|-|s|-|-|-|n|a|-': 'Noun, Singular, Neuter, Accusative',
    'n|n|-|s|-|-|-|n|b|-': 'Noun, Singular, Neuter, Ablative',
    'n|n|-|s|-|-|-|n|d|-': 'Noun, Singular, Neuter, Dative',
    'n|n|-|s|-|-|-|n|g|-': 'Noun, Singular, Neuter, Genitive',
    'n|n|-|s|-|-|-|n|n|-': 'Noun, Singular, Neuter, Nominative',
    'p|p|-|p|-|-|-|f|a|-': 'Pronoun, Plural, Feminine, Accusative',
    'p|p|-|p|-|-|-|f|b|-': 'Pronoun, Plural, Feminine, Ablative',
    'p|p|-|p|-|-|-|f|d|-': 'Pronoun, Plural, Feminine, Dative',
    'p|p|-|p|-|-|-|f|g|-': 'Pronoun, Plural, Feminine, Genitive',
    'p|p|-|p|-|-|-|f|n|-': 'Pronoun, Plural, Feminine, Nominative',
    'p|p|-|p|-|-|-|m|a|-': 'Pronoun, Plural, Masculine, Accusative',
    'p|p|-|p|-|-|-|m|b|-': 'Pronoun, Plural, Masculine, Ablative',
    'p|p|-|p|-|-|-|m|d|-': 'Pronoun, Plural, Masculine, Dative',
    'p|p|-|p|-|-|-|m|g|-': 'Pronoun, Plural, Masculine, Genitive',
    'p|p|-|p|-|-|-|m|n|-': 'Pronoun, Plural, Masculine, Nominative',
    'p|p|-|p|-|-|-|n|a|-': 'Pronoun, Plural, Neuter, Accusative',
    'p|p|-|p|-|-|-|n|b|-': 'Pronoun, Plural, Neuter, Ablative',
    'p|p|-|p|-|-|-|n|d|-': 'Pronoun, Plural, Neuter, Dative',
    'p|p|-|p|-|-|-|n|n|-': 'Pronoun, Plural, Neuter, Nominative',
    'p|p|-|s|-|-|-|f|a|-': 'Pronoun, Singular, Feminine, Accusative',
    'p|p|-|s|-|-|-|f|b|-': 'Pronoun, Singular, Feminine, Ablative',
    'p|p|-|s|-|-|-|f|d|-': 'Pronoun, Singular, Feminine, Dative',
    'p|p|-|s|-|-|-|f|g|-': 'Pronoun, Singular, Feminine, Genitive',
    'p|p|-|s|-|-|-|f|n|-': 'Pronoun, Singular, Feminine, Nominative',
    'p|p|-|s|-|-|-|m|a|-': 'Pronoun, Singular, Masculine, Accusative',
    'p|p|-|s|-|-|-|m|b|-': 'Pronoun, Singular, Masculine, Ablative',
    'p|p|-|s|-|-|-|m|d|-': 'Pronoun, Singular, Masculine, Dative',
    'p|p|-|s|-|-|-|m|g|-': 'Pronoun, Singular, Masculine, Genitive',
    'p|p|-|s|-|-|-|m|n|-': 'Pronoun, Singular, Masculine, Nominative',
    'p|p|-|s|-|-|-|n|a|-': 'Pronoun, Singular, Neuter, Accusative',
    'p|p|-|s|-|-|-|n|b|-': 'Pronoun, Singular, Neuter, Ablative',
    'p|p|-|s|-|-|-|n|d|-': 'Pronoun, Singular, Neuter, Dative',
    'p|p|-|s|-|-|-|n|g|-': 'Pronoun, Singular, Neuter, Genitive',
    'p|p|-|s|-|-|-|n|n|-': 'Pronoun, Singular, Neuter, Nominative',
    'p|p|1|p|-|-|-|f|a|-': 'Pronoun, 1st Person, Plural, Feminine, Accusative',
    'p|p|1|p|-|-|-|f|d|-': 'Pronoun, 1st Person, Plural, Feminine, Dative',
    'p|p|1|p|-|-|-|f|n|-': 'Pronoun, 1st Person, Plural, Feminine, Nominative',
    'p|p|1|p|-|-|-|m|a|-': 'Pronoun, 1st Person, Plural, Masculine, Accusative',
    'p|p|1|p|-|-|-|m|b|-': 'Pronoun, 1st Person, Plural, Masculine, Ablative',
    'p|p|1|p|-|-|-|m|d|-': 'Pronoun, 1st Person, Plural, Masculine, Dative',
    'p|p|1|p|-|-|-|m|g|-': 'Pronoun, 1st Person, Plural, Masculine, Genitive',
    'p|p|1|p|-|-|-|m|n|-': 'Pronoun, 1st Person, Plural, Masculine, Nominative',
    'p|p|1|s|-|-|-|f|a|-': 'Pronoun, 1st Person, Singular, Feminine, Accusative',
    'p|p|1|s|-|-|-|f|d|-': 'Pronoun, 1st Person, Singular, Feminine, Dative',
    'p|p|1|s|-|-|-|f|n|-': 'Pronoun, 1st Person, Singular, Feminine, Nominative',
    'p|p|1|s|-|-|-|m|a|-': 'Pronoun, 1st Person, Singular, Masculine, Accusative',
    'p|p|1|s|-|-|-|m|b|-': 'Pronoun, 1st Person, Singular, Masculine, Ablative',
    'p|p|1|s|-|-|-|m|d|-': 'Pronoun, 1st Person, Singular, Masculine, Dative',
    'p|p|1|s|-|-|-|m|n|-': 'Pronoun, 1st Person, Singular, Masculine, Nominative',
    'p|p|2|p|-|-|-|f|a|-': 'Pronoun, 2nd Person, Plural, Feminine, Accusative',
    'p|p|2|p|-|-|-|f|d|-': 'Pronoun, 2nd Person, Plural, Feminine, Dative',
    'p|p|2|p|-|-|-|f|n|-': 'Pronoun, 2nd Person, Plural, Feminine, Nominative',
    'p|p|2|p|-|-|-|m|a|-': 'Pronoun, 2nd Person, Plural, Masculine, Accusative',
    'p|p|2|p|-|-|-|m|b|-': 'Pronoun, 2nd Person, Plural, Masculine, Ablative',
    'p|p|2|p|-|-|-|m|d|-': 'Pronoun, 2nd Person, Plural, Masculine, Dative',
    'p|p|2|p|-|-|-|m|n|-': 'Pronoun, 2nd Person, Plural, Masculine, Nominative',
    'p|p|2|s|-|-|-|f|a|-': 'Pronoun, 2nd Person, Singular, Feminine, Accusative',
    'p|p|2|s|-|-|-|f|b|-': 'Pronoun, 2nd Person, Singular, Feminine, Ablative',
    'p|p|2|s|-|-|-|f|d|-': 'Pronoun, 2nd Person, Singular, Feminine, Dative',
    'p|p|2|s|-|-|-|f|n|-': 'Pronoun, 2nd Person, Singular, Feminine, Nominative',
    'p|p|2|s|-|-|-|m|a|-': 'Pronoun, 2nd Person, Singular, Masculine, Accusative',
    'p|p|2|s|-|-|-|m|b|-': 'Pronoun, 2nd Person, Singular, Masculine, Ablative',
    'p|p|2|s|-|-|-|m|d|-': 'Pronoun, 2nd Person, Singular, Masculine, Dative',
    'p|p|2|s|-|-|-|m|n|-': 'Pronoun, 2nd Person, Singular, Masculine, Nominative',
    'p|p|2|s|-|-|-|n|d|-': 'Pronoun, 2nd Person, Singular, Neuter, Dative',
    'p|p|3|p|-|-|-|f|a|-': 'Pronoun, 3rd Person, Plural, Feminine, Accusative',
    'p|p|3|p|-|-|-|m|a|-': 'Pronoun, 3rd Person, Plural, Masculine, Accusative',
    'p|p|3|p|-|-|-|m|d|-': 'Pronoun, 3rd Person, Plural, Masculine, Dative',
    'p|p|3|s|-|-|-|f|a|-': 'Pronoun, 3rd Person, Singular, Feminine, Accusative',
    'p|p|3|s|-|-|-|f|d|-': 'Pronoun, 3rd Person, Singular, Feminine, Dative',
    'p|p|3|s|-|-|-|m|a|-': 'Pronoun, 3rd Person, Singular, Masculine, Accusative',
    'p|p|3|s|-|-|-|m|b|-': 'Pronoun, 3rd Person, Singular, Masculine, Ablative',
    'p|p|3|s|-|-|-|m|d|-': 'Pronoun, 3rd Person, Singular, Masculine, Dative',
    'p|p|3|s|-|-|-|n|a|-': 'Pronoun, 3rd Person, Singular, Neuter, Accusative',
    'r|r|-|-|-|-|-|-|-|-': 'Preposition',
    't|t|-|p|f|p|a|m|b|-': 'Participle, Plural, Future, Participle, Active, Masculine, Ablative',
    't|t|-|p|f|p|a|m|n|-': 'Participle, Plural, Future, Participle, Active, Masculine, Nominative',
    't|t|-|p|f|p|a|n|a|-': 'Participle, Plural, Future, Participle, Active, Neuter, Accusative',
    't|t|-|p|p|g|p|f|a|-': 'Participle, Plural, Present, Gerundive, Passive, Feminine, Accusative',
    't|t|-|p|p|g|p|n|a|-': 'Participle, Plural, Present, Gerundive, Passive, Neuter, Accusative',
    't|t|-|p|p|p|a|f|a|-': 'Participle, Plural, Present, Participle, Active, Feminine, Accusative',
    't|t|-|p|p|p|a|f|b|-': 'Participle, Plural, Present, Participle, Active, Feminine, Ablative',
    't|t|-|p|p|p|a|f|n|-': 'Participle, Plural, Present, Participle, Active, Feminine, Nominative',
    't|t|-|p|p|p|a|m|a|-': 'Participle, Plural, Present, Participle, Active, Masculine, Accusative',
    't|t|-|p|p|p|a|m|b|-': 'Participle, Plural, Present, Participle, Active, Masculine, Ablative',
    't|t|-|p|p|p|a|m|b|s':
      'Participle, Plural, Present, Participle, Active, Masculine, Ablative, Superlative',
    't|t|-|p|p|p|a|m|n|-': 'Participle, Plural, Present, Participle, Active, Masculine, Nominative',
    't|t|-|p|p|p|a|n|a|-': 'Participle, Plural, Present, Participle, Active, Neuter, Accusative',
    't|t|-|p|p|p|a|n|b|-': 'Participle, Plural, Present, Participle, Active, Neuter, Ablative',
    't|t|-|p|r|p|a|m|n|-': 'Participle, Plural, Perfect, Participle, Active, Masculine, Nominative',
    't|t|-|p|r|p|p|f|a|-': 'Participle, Plural, Perfect, Participle, Passive, Feminine, Accusative',
    't|t|-|p|r|p|p|f|b|-': 'Participle, Plural, Perfect, Participle, Passive, Feminine, Ablative',
    't|t|-|p|r|p|p|f|n|-': 'Participle, Plural, Perfect, Participle, Passive, Feminine, Nominative',
    't|t|-|p|r|p|p|m|a|-': 'Participle, Plural, Perfect, Participle, Passive, Masculine, Accusative',
    't|t|-|p|r|p|p|m|b|-': 'Participle, Plural, Perfect, Participle, Passive, Masculine, Ablative',
    't|t|-|p|r|p|p|m|d|-': 'Participle, Plural, Perfect, Participle, Passive, Masculine, Dative',
    't|t|-|p|r|p|p|m|g|-': 'Participle, Plural, Perfect, Participle, Passive, Masculine, Genitive',
    't|t|-|p|r|p|p|m|n|-': 'Participle, Plural, Perfect, Participle, Passive, Masculine, Nominative',
    't|t|-|p|r|p|p|n|a|-': 'Participle, Plural, Perfect, Participle, Passive, Neuter, Accusative',
    't|t|-|p|r|p|p|n|b|-': 'Participle, Plural, Perfect, Participle, Passive, Neuter, Ablative',
    't|t|-|p|r|p|p|n|n|-': 'Participle, Plural, Perfect, Participle, Passive, Neuter, Nominative',
    't|t|-|s|f|p|a|f|b|-': 'Participle, Singular, Future, Participle, Active, Feminine, Ablative',
    't|t|-|s|f|p|a|m|a|-': 'Participle, Singular, Future, Participle, Active, Masculine, Accusative',
    't|t|-|s|f|p|a|m|b|-': 'Participle, Singular, Future, Participle, Active, Masculine, Ablative',
    't|t|-|s|f|p|a|m|n|-': 'Participle, Singular, Future, Participle, Active, Masculine, Nominative',
    't|t|-|s|p|d|p|f|a|-': 'Participle, Singular, Present, Gerund, Passive, Feminine, Accusative',
    't|t|-|s|p|d|p|n|a|-': 'Participle, Singular, Present, Gerund, Passive, Neuter, Accusative',
    't|t|-|s|p|d|p|n|b|-': 'Participle, Singular, Present, Gerund, Passive, Neuter, Ablative',
    't|t|-|s|p|d|p|n|g|-': 'Participle, Singular, Present, Gerund, Passive, Neuter, Genitive',
    't|t|-|s|p|d|p|n|n|-': 'Participle, Singular, Present, Gerund, Passive, Neuter, Nominative',
    't|t|-|s|p|g|p|f|a|-': 'Participle, Singular, Present, Gerundive, Passive, Feminine, Accusative',
    't|t|-|s|p|g|p|m|b|-': 'Participle, Singular, Present, Gerundive, Passive, Masculine, Ablative',
    't|t|-|s|p|p|a|f|a|-': 'Participle, Singular, Present, Participle, Active, Feminine, Accusative',
    't|t|-|s|p|p|a|f|b|-': 'Participle, Singular, Present, Participle, Active, Feminine, Ablative',
    't|t|-|s|p|p|a|f|n|-': 'Participle, Singular, Present, Participle, Active, Feminine, Nominative',
    't|t|-|s|p|p|a|m|a|-': 'Participle, Singular, Present, Participle, Active, Masculine, Accusative',
    't|t|-|s|p|p|a|m|a|s':
      'Participle, Singular, Present, Participle, Active, Masculine, Accusative, Superlative',
    't|t|-|s|p|p|a|m|b|-': 'Participle, Singular, Present, Participle, Active, Masculine, Ablative',
    't|t|-|s|p|p|a|m|b|s':
      'Participle, Singular, Present, Participle, Active, Masculine, Ablative, Superlative',
    't|t|-|s|p|p|a|m|g|-': 'Participle, Singular, Present, Participle, Active, Masculine, Genitive',
    't|t|-|s|p|p|a|m|n|-': 'Participle, Singular, Present, Participle, Active, Masculine, Nominative',
    't|t|-|s|p|p|a|m|n|s':
      'Participle, Singular, Present, Participle, Active, Masculine, Nominative, Superlative',
    't|t|-|s|p|p|a|n|b|-': 'Participle, Singular, Present, Participle, Active, Neuter, Ablative',
    't|t|-|s|p|p|a|n|n|-': 'Participle, Singular, Present, Participle, Active, Neuter, Nominative',
    't|t|-|s|r|p|a|m|n|-': 'Participle, Singular, Perfect, Participle, Active, Masculine, Nominative',
    't|t|-|s|r|p|a|n|a|-': 'Participle, Singular, Perfect, Participle, Active, Neuter, Accusative',
    't|t|-|s|r|p|p|f|a|-': 'Participle, Singular, Perfect, Participle, Passive, Feminine, Accusative',
    't|t|-|s|r|p|p|f|b|-': 'Participle, Singular, Perfect, Participle, Passive, Feminine, Ablative',
    't|t|-|s|r|p|p|f|d|-': 'Participle, Singular, Perfect, Participle, Passive, Feminine, Dative',
    't|t|-|s|r|p|p|f|g|-': 'Participle, Singular, Perfect, Participle, Passive, Feminine, Genitive',
    't|t|-|s|r|p|p|f|n|-': 'Participle, Singular, Perfect, Participle, Passive, Feminine, Nominative',
    't|t|-|s|r|p|p|m|a|-': 'Participle, Singular, Perfect, Participle, Passive, Masculine, Accusative',
    't|t|-|s|r|p|p|m|b|-': 'Participle, Singular, Perfect, Participle, Passive, Masculine, Ablative',
    't|t|-|s|r|p|p|m|d|-': 'Participle, Singular, Perfect, Participle, Passive, Masculine, Dative',
    't|t|-|s|r|p|p|m|g|-': 'Participle, Singular, Perfect, Participle, Passive, Masculine, Genitive',
    't|t|-|s|r|p|p|m|n|-': 'Participle, Singular, Perfect, Participle, Passive, Masculine, Nominative',
    't|t|-|s|r|p|p|m|v|-': 'Participle, Singular, Perfect, Participle, Passive, Masculine, Vocative',
    't|t|-|s|r|p|p|n|a|-': 'Participle, Singular, Perfect, Participle, Passive, Neuter, Accusative',
    't|t|-|s|r|p|p|n|b|-': 'Participle, Singular, Perfect, Participle, Passive, Neuter, Ablative',
    't|t|-|s|r|p|p|n|d|-': 'Participle, Singular, Perfect, Participle, Passive, Neuter, Dative',
    't|t|-|s|r|p|p|n|g|-': 'Participle, Singular, Perfect, Participle, Passive, Neuter, Genitive',
    't|t|-|s|r|p|p|n|n|-': 'Participle, Singular, Perfect, Participle, Passive, Neuter, Nominative',
    'v|v|-|-|f|n|a|-|-|-': 'Verb, Future, Infinitive, Active',
    'v|v|-|-|p|n|a|-|-|-': 'Verb, Present, Infinitive, Active',
    'v|v|-|-|p|n|p|-|-|-': 'Verb, Present, Infinitive, Passive',
    'v|v|-|-|r|n|a|-|-|-': 'Verb, Perfect, Infinitive, Active',
    'v|v|1|p|i|s|a|-|-|-': 'Verb, 1st Person, Plural, Imperfect, Subjunctive, Active',
    'v|v|1|p|l|s|a|-|-|-': 'Verb, 1st Person, Plural, Pluperfect, Subjunctive, Active',
    'v|v|1|p|p|i|a|-|-|-': 'Verb, 1st Person, Plural, Present, Indicative, Active',
    'v|v|1|p|p|i|p|-|-|-': 'Verb, 1st Person, Plural, Present, Indicative, Passive',
    'v|v|1|p|p|s|a|-|-|-': 'Verb, 1st Person, Plural, Present, Subjunctive, Active',
    'v|v|1|p|p|s|p|-|-|-': 'Verb, 1st Person, Plural, Present, Subjunctive, Passive',
    'v|v|1|p|r|i|a|-|-|-': 'Verb, 1st Person, Plural, Perfect, Indicative, Active',
    'v|v|1|p|t|i|a|-|-|-': 'Verb, 1st Person, Plural, Future Perfect, Indicative, Active',
    'v|v|1|s|f|i|a|-|-|-': 'Verb, 1st Person, Singular, Future, Indicative, Active',
    'v|v|1|s|i|s|a|-|-|-': 'Verb, 1st Person, Singular, Imperfect, Subjunctive, Active',
    'v|v|1|s|l|s|a|-|-|-': 'Verb, 1st Person, Singular, Pluperfect, Subjunctive, Active',
    'v|v|1|s|p|i|a|-|-|-': 'Verb, 1st Person, Singular, Present, Indicative, Active',
    'v|v|1|s|p|i|p|-|-|-': 'Verb, 1st Person, Singular, Present, Indicative, Passive',
    'v|v|1|s|p|s|a|-|-|-': 'Verb, 1st Person, Singular, Present, Subjunctive, Active',
    'v|v|1|s|p|s|p|-|-|-': 'Verb, 1st Person, Singular, Present, Subjunctive, Passive',
    'v|v|1|s|r|i|a|-|-|-': 'Verb, 1st Person, Singular, Perfect, Indicative, Active',
    'v|v|1|s|t|i|a|-|-|-': 'Verb, 1st Person, Singular, Future Perfect, Indicative, Active',
    'v|v|2|p|i|s|a|-|-|-': 'Verb, 2nd Person, Plural, Imperfect, Subjunctive, Active',
    'v|v|2|p|l|s|a|-|-|-': 'Verb, 2nd Person, Plural, Pluperfect, Subjunctive, Active',
    'v|v|2|p|p|i|a|-|-|-': 'Verb, 2nd Person, Plural, Present, Indicative, Active',
    'v|v|2|p|p|i|p|-|-|-': 'Verb, 2nd Person, Plural, Present, Indicative, Passive',
    'v|v|2|p|p|s|a|-|-|-': 'Verb, 2nd Person, Plural, Present, Subjunctive, Active',
    'v|v|2|p|r|i|a|-|-|-': 'Verb, 2nd Person, Plural, Perfect, Indicative, Active',
    'v|v|2|p|r|s|a|-|-|-': 'Verb, 2nd Person, Plural, Perfect, Subjunctive, Active',
    'v|v|2|p|t|i|a|-|-|-': 'Verb, 2nd Person, Plural, Future Perfect, Indicative, Active',
    'v|v|2|s|i|s|a|-|-|-': 'Verb, 2nd Person, Singular, Imperfect, Subjunctive, Active',
    'v|v|2|s|p|i|a|-|-|-': 'Verb, 2nd Person, Singular, Present, Indicative, Active',
    'v|v|2|s|p|i|p|-|-|-': 'Verb, 2nd Person, Singular, Present, Indicative, Passive',
    'v|v|2|s|p|m|a|-|-|-': 'Verb, 2nd Person, Singular, Present, Imperative, Active',
    'v|v|2|s|p|s|a|-|-|-': 'Verb, 2nd Person, Singular, Present, Subjunctive, Active',
    'v|v|2|s|p|s|p|-|-|-': 'Verb, 2nd Person, Singular, Present, Subjunctive, Passive',
    'v|v|2|s|r|i|a|-|-|-': 'Verb, 2nd Person, Singular, Perfect, Indicative, Active',
    'v|v|2|s|t|i|a|-|-|-': 'Verb, 2nd Person, Singular, Future Perfect, Indicative, Active',
    'v|v|3|p|f|i|a|-|-|-': 'Verb, 3rd Person, Plural, Future, Indicative, Active',
    'v|v|3|p|i|i|a|-|-|-': 'Verb, 3rd Person, Plural, Imperfect, Indicative, Active',
    'v|v|3|p|i|s|a|-|-|-': 'Verb, 3rd Person, Plural, Imperfect, Subjunctive, Active',
    'v|v|3|p|l|i|a|-|-|-': 'Verb, 3rd Person, Plural, Pluperfect, Indicative, Active',
    'v|v|3|p|l|s|a|-|-|-': 'Verb, 3rd Person, Plural, Pluperfect, Subjunctive, Active',
    'v|v|3|p|p|i|a|-|-|-': 'Verb, 3rd Person, Plural, Present, Indicative, Active',
    'v|v|3|p|p|i|p|-|-|-': 'Verb, 3rd Person, Plural, Present, Indicative, Passive',
    'v|v|3|p|p|s|a|-|-|-': 'Verb, 3rd Person, Plural, Present, Subjunctive, Active',
    'v|v|3|p|p|s|p|-|-|-': 'Verb, 3rd Person, Plural, Present, Subjunctive, Passive',
    'v|v|3|p|r|i|a|-|-|-': 'Verb, 3rd Person, Plural, Perfect, Indicative, Active',
    'v|v|3|p|t|i|a|-|-|-': 'Verb, 3rd Person, Plural, Future Perfect, Indicative, Active',
    'v|v|3|s|i|i|a|-|-|-': 'Verb, 3rd Person, Singular, Imperfect, Indicative, Active',
    'v|v|3|s|i|i|p|-|-|-': 'Verb, 3rd Person, Singular, Imperfect, Indicative, Passive',
    'v|v|3|s|i|s|a|-|-|-': 'Verb, 3rd Person, Singular, Imperfect, Subjunctive, Active',
    'v|v|3|s|i|s|p|-|-|-': 'Verb, 3rd Person, Singular, Imperfect, Subjunctive, Passive',
    'v|v|3|s|l|i|a|-|-|-': 'Verb, 3rd Person, Singular, Pluperfect, Indicative, Active',
    'v|v|3|s|l|s|a|-|-|-': 'Verb, 3rd Person, Singular, Pluperfect, Subjunctive, Active',
    'v|v|3|s|p|i|a|-|-|-': 'Verb, 3rd Person, Singular, Present, Indicative, Active',
    'v|v|3|s|p|i|p|-|-|-': 'Verb, 3rd Person, Singular, Present, Indicative, Passive',
    'v|v|3|s|p|s|a|-|-|-': 'Verb, 3rd Person, Singular, Present, Subjunctive, Active',
    'v|v|3|s|p|s|p|-|-|-': 'Verb, 3rd Person, Singular, Present, Subjunctive, Passive',
    'v|v|3|s|r|i|a|-|-|-': 'Verb, 3rd Person, Singular, Perfect, Indicative, Active',
    'v|v|3|s|t|i|a|-|-|-': 'Verb, 3rd Person, Singular, Future Perfect, Indicative, Active'
  };
  return true;
}
