import { southAsianState } from './south-asian.state.mjs';
export function initializeSouthAsian() {
  southAsianState.XPOS_ARABIC = {
    "''": 'Closing Quote',
    '(': 'Opening Parenthesis',
    ')': 'Closing Parenthesis',
    ',': 'Comma',
    '-': 'Dash',
    '.': 'Period',
    '...': 'Ellipsis',
    ':': 'Colon',
    CC: 'Coordinating Conjunction',
    CD: 'Cardinal Number',
    DT: 'Determiner',
    EX: 'Existential Particle',
    IN: 'Preposition / Subordinating Conjunction',
    JJ: 'Adjective',
    JJR: 'Adjective, Comparative',
    NN: 'Noun',
    NNP: 'Proper Noun',
    PDEM: 'Demonstrative Pronoun',
    PDT: 'Predeterminer',
    PRP: 'Personal Pronoun',
    RB: 'Adverb',
    REL: 'Relative Pronoun',
    RP: 'Particle',
    SYM: 'Symbol',
    UH: 'Interjection',
    VBC: 'Verb, Conjugated',
    VBG: 'Verb, Gerund / Participle',
    VBN: 'Verb, Past Participle',
    WDT: 'Relative / Interrogative Determiner',
    WP: 'Relative / Interrogative Pronoun',
    WRB: 'Relative / Interrogative Adverb',
    '``': 'Opening Quote'
  };
  southAsianState.XPOS_HINDI = {
    "''": 'Closing Quote',
    '(': 'Opening Parenthesis',
    ')': 'Closing Parenthesis',
    ',': 'Comma',
    '-': 'Dash',
    '.': 'Period',
    '...': 'Ellipsis',
    '/': 'Slash',
    ':': 'Colon',
    CC: 'Coordinating Conjunction',
    CD: 'Cardinal Number',
    DRE: 'Relative Determiner',
    DT: 'Determiner',
    DTI: 'Indefinite Determiner',
    EMPH: 'Emphatic Particle',
    GW: 'Goes-With (Partial Word)',
    HON: 'Honorific',
    IN: 'Postposition',
    JJ: 'Adjective',
    JJR: 'Adjective, Comparative',
    JJS: 'Adjective, Superlative',
    LS: 'List Marker',
    NEG: 'Negation',
    NFP: 'Non-Final Punctuation',
    NN: 'Common Noun',
    NNP: 'Proper Noun',
    NST: 'Spatial / Temporal Noun',
    PDEM: 'Demonstrative Pronoun',
    PRI: 'Indefinite Pronoun',
    PRP: 'Personal Pronoun',
    PRP$: 'Possessive Pronoun',
    PRR: 'Relative Pronoun',
    PRT: 'Particle',
    QF: 'Quantifier',
    RB: 'Adverb',
    REL: 'Relative Marker',
    SFA: 'Adjectival Suffix',
    SFN: 'Nominal Suffix',
    SFV: 'Verbal Suffix',
    SYM: 'Symbol',
    UH: 'Interjection',
    VB: 'Verb',
    VBC: 'Verb, Compound',
    VBI: 'Verb, Intransitive',
    VBN: 'Verb, Past Participle',
    VINF: 'Verb, Infinitive',
    VN: 'Verbal Noun',
    VXH: 'Auxiliary Verb (Honā)',
    WDT: 'Relative / Interrogative Determiner',
    WP: 'Relative / Interrogative Pronoun',
    XX: 'Unknown',
    '``': 'Opening Quote'
  };
  southAsianState.XPOS_PERSIAN = {
    ADJ: 'Adjective',
    ADJ_CMPR: 'Adjective, Comparative',
    ADJ_INO: 'Adjective, Other',
    ADJ_SUP: 'Adjective, Superlative',
    ADV: 'Adverb',
    ADV_COMP: 'Adverb, Comparative',
    ADV_I: 'Adverb, Interrogative',
    ADV_LOC: 'Adverb, Locative',
    ADV_NEG: 'Adverb, Negative',
    ADV_TIME: 'Adverb, Temporal',
    CLITIC: 'Enclitic Pronoun',
    CON: 'Conjunction',
    CONJ: 'Conjunction',
    DELM: 'Punctuation / Delimiter',
    DET: 'Determiner',
    FW: 'Foreign Word',
    INT: 'Interjection',
    NUM: 'Numeral',
    N_PL: 'Noun, Plural',
    N_SING: 'Noun, Singular',
    N_VOC: 'Noun, Vocative',
    P: 'Preposition',
    PREV: 'Preverb (Verbal Prefix)',
    PRO: 'Pronoun',
    V_AUX: 'Auxiliary Verb',
    V_IMP: 'Verb, Imperative',
    V_PA: 'Verb, Past Stem',
    V_PP: 'Verb, Past Participle',
    V_PRS: 'Verb, Present Stem',
    V_SUB: 'Verb, Subjunctive'
  };
  southAsianState.XPOS_INDONESIAN = {
    APP: 'Apposition Marker',
    ASP: 'Aspect Marker',
    'ASP+PS2': 'Aspect Marker + 2nd Person Possessive',
    'ASP+PS3': 'Aspect Marker + 3rd Person Possessive',
    'ASP+T--': 'Aspect Marker Classifier / Measure Word',
    ASS: 'Associative Marker',
    'ASS+PS3': 'Associative Marker + 3rd Person Possessive',
    'B--': 'Adverb',
    'B--+PS3': 'Adverb + 3rd Person Possessive',
    'B--+T--': 'Adverb Classifier / Measure Word',
    'CC-': 'Coordinating Conjunction',
    'CC-+PS3': 'Coordinating Conjunction + 3rd Person Possessive',
    'CC-+T--': 'Coordinating Conjunction Classifier / Measure Word',
    'CD-': 'Cardinal Number',
    'CD-+PS3': 'Cardinal Number + 3rd Person Possessive',
    'CO-': 'Subordinating Conjunction',
    'CO-+PS3': 'Subordinating Conjunction + 3rd Person Possessive',
    'D--': 'Determiner',
    'D--+PS2': 'Determiner + 2nd Person Possessive',
    'D--+PS3': 'Determiner + 3rd Person Possessive',
    'D--+T--': 'Determiner Classifier / Measure Word',
    'F--': 'Adjective',
    'F--+PS1': 'Adjective + 1st Person Possessive',
    'F--+PS2': 'Adjective + 2nd Person Possessive',
    'F--+PS3': 'Adjective + 3rd Person Possessive',
    'F--+T--': 'Adjective Classifier / Measure Word',
    'G--': 'Cardinal Number',
    'G--+PS3': 'Cardinal Number + 3rd Person Possessive',
    'G--+T--': 'Cardinal Number Classifier / Measure Word',
    'H--': 'Pronoun',
    'H--+T--': 'Pronoun Classifier / Measure Word',
    'I--': 'Interjection',
    'M--': 'Modal / Auxiliary',
    'M--+PS3': 'Modal / Auxiliary + 3rd Person Possessive',
    'M--+T--': 'Modal / Auxiliary Classifier / Measure Word',
    NPD: 'Noun, Plural Definite',
    'NPD+PS2': 'Noun, Plural Definite + 2nd Person Possessive',
    'NPD+PS3': 'Noun, Plural Definite + 3rd Person Possessive',
    NSD: 'Noun, Singular Definite',
    'NSD+PS1': 'Noun, Singular Definite + 1st Person Possessive',
    'NSD+PS2': 'Noun, Singular Definite + 2nd Person Possessive',
    'NSD+PS3': 'Noun, Singular Definite + 3rd Person Possessive',
    'NSD+T--': 'Noun, Singular Definite Classifier / Measure Word',
    NSF: 'Noun, Singular Feminine',
    NSM: 'Noun, Singular Mass',
    'NSM+PS3': 'Noun, Singular Mass + 3rd Person Possessive',
    NSP: 'Noun, Singular Partitive',
    'O--': 'Other / Residual',
    PP1: '+ 1st Person Pronoun',
    'PP1+T--': '+ 1st Person Pronoun Classifier / Measure Word',
    PP2: '+ 2nd Person Pronoun',
    PP3: '+ 3rd Person Pronoun',
    'PP3+T--': '+ 3rd Person Pronoun Classifier / Measure Word',
    PS1: '+ 1st Person Possessive',
    'PS1+VSA': '+ 1st Person Possessive Verb, Simple Active',
    'PS1+VSA+T--': '+ 1st Person Possessive Verb, Simple Active Classifier / Measure Word',
    PS2: '+ 2nd Person Possessive',
    'PS2+VSA': '+ 2nd Person Possessive Verb, Simple Active',
    PS3: '+ 3rd Person Possessive',
    'R--': 'Preposition',
    'R--+PS1': 'Preposition + 1st Person Possessive',
    'R--+PS2': 'Preposition + 2nd Person Possessive',
    'R--+PS3': 'Preposition + 3rd Person Possessive',
    'S--': 'Proper Noun',
    'S--+PS3': 'Proper Noun + 3rd Person Possessive',
    'T--': 'Classifier / Measure Word',
    VPA: 'Verb, Prefix Active',
    VSA: 'Verb, Simple Active',
    'VSA+PS1': 'Verb, Simple Active + 1st Person Possessive',
    'VSA+PS2': 'Verb, Simple Active + 2nd Person Possessive',
    'VSA+PS3': 'Verb, Simple Active + 3rd Person Possessive',
    'VSA+T--': 'Verb, Simple Active Classifier / Measure Word',
    VSP: 'Verb, Simple Passive',
    'VSP+PS3': 'Verb, Simple Passive + 3rd Person Possessive',
    'VSP+T--': 'Verb, Simple Passive Classifier / Measure Word',
    'W--': 'Particle',
    'W--+T--': 'Particle Classifier / Measure Word',
    'X--': 'Unknown / Foreign',
    'Z--': 'Punctuation'
  };
  return true;
}
