import { westernState } from './western.state.mjs';
export function initializeWestern() {
  westernState.XPOS_IRISH = {
    '!': 'Exclamation Mark',
    "'": 'Apostrophe / Quote',
    '.': 'Period',
    '..': 'Double Period',
    '...': 'Ellipsis',
    '?': 'Question Mark',
    Abbr: 'Abbreviation',
    'Abbr=Yes': 'Abbreviation (Feature Leak)',
    Abr: 'Abbreviation',
    Ad: 'Adverb (Verbal Particle)',
    Adj: 'Adjective',
    Art: 'Article',
    CM: 'Complementizer',
    CU: 'Complementizer (That / Which)',
    Cmp: 'Comparative Particle',
    Cmpd: 'Compound Word',
    CmpdNoGen: 'Compound (No Genitive)',
    Comp: 'Complementizer',
    Cond: 'Conditional Mood',
    Coord: 'Coordinating Conjunction',
    Cop: 'Copula',
    Cp: 'Conjunction Particle',
    Deg: 'Degree Word',
    Dem: 'Demonstrative',
    Det: 'Determiner',
    Dir: 'Directional Particle',
    Foreign: 'Foreign Word',
    FutInd: 'Future Indicative',
    Gn: 'Genitive Particle',
    Idf: 'Indefinite Pronoun',
    Imper: 'Imperative',
    Inf: 'Infinitive Particle',
    Item: 'List Item',
    Itj: 'Interjection',
    Its: 'Particle (Is / It)',
    Loc: 'Locative Particle',
    Nm: 'Numeral Marker',
    Nooun: 'Noun (Typo Variant)',
    Noun: 'Noun',
    'NounCase=Nom|': 'Noun, Nominative (Feature Leak)',
    Num: 'Numeral',
    PastImp: 'Past Habitual',
    PastInd: 'Past Indicative',
    Pat: 'Patronymic Particle (Ó / Mac)',
    Pers: 'Personal Pronoun',
    Poss: 'Possessive',
    Prep: 'Preposition',
    PresImp: 'Present Habitual',
    PresInd: 'Present Indicative',
    PresSubj: 'Present Subjunctive',
    Pron: 'Pronoun',
    Punct: 'Punctuation',
    Q: 'Question Particle',
    Ref: 'Reflexive',
    Rel: 'Relative Particle',
    SIMP: 'Simple Preposition',
    Simp: 'Simple Preposition',
    Subord: 'Subordinating Conjunction',
    Subst: 'Substantive Verb',
    Sup: 'Superlative',
    Temp: 'Temporal Particle',
    Unknown: 'Unknown',
    VD: 'Verb, Past (Dependent)',
    VI: 'Verb, Imperative',
    VT: 'Verb, Past (Independent)',
    VTI: 'Verb, Past (Independent, Intransitive)',
    Vb: 'Verb',
    Verb: 'Verb',
    Voc: 'Vocative Particle',
    Web: 'Web Address / URL',
    X: 'Foreign / Unknown',
    cionn: 'Compound Preposition Element (Cionn)',
    punct: 'Punctuation (Lowercase)'
  };
  westernState.XPOS_ITALIAN = {
    A: 'Adjective',
    ADJ: 'Adjective (UPOS)',
    AP: 'Possessive Adjective',
    B: 'Adverb',
    BN: 'Negative Adverb',
    CC: 'Coordinating Conjunction',
    CS: 'Subordinating Conjunction',
    DD: 'Demonstrative Determiner',
    DE: 'Prepositional Article',
    DI: 'Indefinite Determiner',
    DQ: 'Interrogative Determiner',
    E: 'Preposition',
    FB: 'Balanced Punctuation (Brackets / Quotes)',
    FC: 'Comma',
    FF: 'Slash / Other Punctuation',
    FS: 'Sentence-Final Punctuation',
    I: 'Interjection',
    N: 'Cardinal Number',
    NO: 'Ordinal Number',
    NOUN: 'Noun',
    PC: 'Clitic Pronoun',
    PD: 'Demonstrative Pronoun',
    PE: 'Personal Pronoun',
    PI: 'Indefinite Pronoun',
    PP: 'Possessive Pronoun',
    PQ: 'Interrogative Pronoun',
    PR: 'Relative Pronoun',
    PRON: 'Pronoun',
    RD: 'Definite Article',
    RI: 'Indefinite Article',
    S: 'Common Noun',
    SP: 'Proper Noun',
    SW: 'Foreign Word',
    SYM: 'Symbol',
    T: 'Predeterminer / Title',
    V: 'Main Verb',
    VA: 'Auxiliary Verb',
    VM: 'Modal Verb',
    X: 'Residual / Other'
  };
  westernState.XPOS_TURKISH = {
    '-': 'Dash / Hyphen',
    ADj: 'Adjective (Typo)',
    ANum: 'Adjectival Numeral',
    Abbr: 'Abbreviation',
    Abr: 'Abbreviation',
    Adj: 'Adjective',
    Advmod: 'Adverbial Modifier',
    Anum: 'Adjectival Numeral',
    Attr: 'Attributive',
    Aux: 'Auxiliary',
    COnv: 'Converb (Typo)',
    CPar: 'Closing Parenthesis',
    Comma: 'Comma',
    Comv: 'Comitative',
    Conj: 'Conjunction',
    Conv: 'Converb (Adverbial Participle)',
    Demons: 'Demonstrative',
    Det: 'Determiner',
    Dup: 'Reduplication',
    Emph: 'Emphatic',
    Excl: 'Exclamation Mark',
    ExclDots: 'exclamation+ellipsis',
    Exist: 'Existential (Var / Yok)',
    ExistConv: 'Existential Converb',
    ExistPtcp: 'Existential Participle',
    ExistVnoun: 'Existential Verbal Noun',
    Expr: 'Expressive / Onomatopoeia',
    Indef: 'Indefinite',
    Inst: 'Instrumental',
    Interj: 'Interjection',
    List: 'List Marker',
    NAdj: 'Nominal Adjective',
    NNum: 'Nominal Numeral',
    NOUN: 'Noun',
    Neg: 'Negation',
    Ness: 'Derivational Suffix',
    Nnum: 'Nominal Numeral',
    OPar: 'Opening Parenthesis',
    OVert: 'Overt Subject (Typo)',
    Overt: 'Overt Subject',
    P: 'Pronoun',
    'P;lace': 'Place (Typo)',
    PCAbl: 'Pronominal Clitic, Ablative',
    PCAcc: 'Pronominal Clitic, Accusative',
    PCDat: 'Pronominal Clitic, Dative',
    PCGen: 'Pronominal Clitic, Genitive',
    PCIns: 'Pronominal Clitic, Instrumental',
    PCNom: 'Pronominal Clitic, Nominative',
    PROPN: 'Proper Noun',
    Part: 'Particle',
    Partic: 'Particle',
    Pers: 'Personal Pronoun',
    Place: 'Place Name / Locative',
    Ptcp: 'Participle',
    Punc: 'Punctuation',
    Quan: 'Quantifier',
    Quant: 'Quantifier',
    Ques: 'Question Particle',
    QuesDots: 'question+ellipsis',
    Quest: 'Question',
    Recip: 'Reciprocal',
    Reflex: 'Reflexive',
    Rel: 'Relative',
    Separ: 'Separator Punctuation',
    Since: 'Temporal',
    Stop: 'Period',
    TDots: 'Ellipsis',
    Topic: 'Topic Marker',
    Typo: 'Typographical Error',
    Venoun: 'Verbal Noun (Typo)',
    Vnoun: 'Verbal Noun',
    Vnouon: 'Verbal Noun (Typo)',
    Web: 'URL / Web Address',
    With: 'Comitative (With)',
    Without: 'Abessive (Without)',
    YEar: 'Year (Typo)',
    Year: 'Year',
    Yer: 'Year (Typo)',
    Zer: 'Zero Copula',
    Zero: 'Zero Copula',
    Zerp: 'Zero Copula (Typo)',
    Zerı: 'Zero Copula',
    a: 'Adjective',
    det: 'Determiner',
    exist: 'Existential',
    noun: 'Noun',
    place: 'Place',
    prop: 'Proper Noun',
    ptcp: 'Participle',
    punc: 'Punctuation',
    verb: 'Verb',
    vnoun: 'Verbal Noun'
  };
  return true;
}
