from __future__ import annotations

from pathlib import Path

import assign_coarse_tags_to_user_grouped_5050_no_cultural_bucket as base


BASE_DIR = Path(__file__).resolve().parent
OUT_DIR = BASE_DIR / "derived_fasttext_categories"

base.SUMMARY_OUT = OUT_DIR / "extended_manual_seed_no_cultural_bucket_summary.tsv"
base.TAG_MAP_OUT = OUT_DIR / "extended_manual_seed_no_cultural_bucket_tag_map.tsv"
base.TOP10_OUT = OUT_DIR / "extended_manual_seed_no_cultural_bucket_top10_attracted.tsv"
base.REPORT_OUT = OUT_DIR / "extended_manual_seed_no_cultural_bucket_top10_attracted.md"

base.USER_GROUPS = [
    (
        "PERSON",
        [
            "person",
            "deity",
            "religious figure",
            "character",
            "nickname",
            "persons",
            "historical figure",
            "politician",
            "pessoa",
            "شخص",
            "god",
            "mythological figure",
        ],
    ),
    (
        "GROUP",
        [
            "nationality",
            "group",
            "ethnic group",
            "demographic group",
            "social group",
            "group of people",
            "people",
            "demographic",
            "political group",
            "religious group",
        ],
    ),
    (
        "TITLE / ROLE",
        [
            "title",
            "profession",
            "position",
            "occupation",
            "job title",
            "political position",
            "role",
            "government position",
            "military rank",
            "religious title",
        ],
    ),
    (
        "LOCATION",
        [
            "location",
            "country",
            "city",
            "region",
            "state",
            "continent",
            "building",
            "province",
            "facility",
            "district",
            "river",
            "geographic region",
            "administrative region",
            "geopolitical entity",
            "administrative division",
            "village",
            "geographical feature",
            "geographical region",
            "place",
            "geopolitical region",
            "street",
            "hospital",
            "infrastructure",
            "diocese",
            "celestial body",
            "universe",
        ],
    ),
    (
        "ORGANIZATION",
        [
            "organization",
            "media",
            "political party",
            "government organization",
            "political organization",
            "website",
            "educational institution",
            "social media platform",
            "sports team",
            "news agency",
            "political entity",
            "government agency",
            "religious organization",
            "company",
            "government",
            "media outlet",
            "media organization",
            "military organization",
            "sports club",
            "news organization",
            "government ministry",
            "university",
            "international organization",
            "law enforcement agency",
            "court",
            "government body",
            "legislative body",
            "institution",
            "military unit",
            "financial institution",
            "football club",
            "sports organization",
            "government department",
            "organization type",
            "governmental organization",
            "team",
            "dynasty",
        ],
    ),
    (
        "TIME",
        [
            "date",
            "time period",
            "year",
            "time",
            "duration",
            "day of the week",
            "month",
            "time duration",
            "historical period",
            "date range",
            "day of week",
            "season",
        ],
    ),
    (
        "QUANTITY",
        [
            "quantity",
            "measurement",
            "currency",
            "percentage",
            "age",
            "statistic",
            "monetary value",
            "score",
            "number",
            "price",
            "currency amount",
            "distance",
            "statistics",
            "quantities",
            "ranking",
            "ordinal number",
        ],
    ),
    (
        "EVENT",
        [
            "event",
            "historical event",
            "cultural event",
            "festival",
            "sports event",
            "political event",
            "holiday",
            "natural disaster",
        ],
    ),
    (
        "WORK_OF_ART",
        [
            "work of art",
            "film",
            "literary work",
            "video game",
            "tv show",
            "music genre",
            "art form",
            "song",
            "book",
            "tv series",
            "genre",
            "film title",
            "publication",
            "religious text",
        ],
    ),
    (
        "PRODUCT",
        [
            "product",
            "technology",
            "brand",
            "food",
            "service",
            "platform",
            "operating system",
            "vehicle",
            "weapon",
            "software",
            "product category",
            "application",
            "object",
            "vehicle type",
            "food product",
            "agricultural product",
            "musical instrument",
            "commodity",
            "product type",
            "transportation",
        ],
    ),
    (
        "CONCEPT",
        [
            "scientific concept",
            "concept",
            "medical condition",
            "disease",
            "legal concept",
            "economic concept",
            "cultural concept",
            "field of study",
            "financial concept",
            "philosophical concept",
            "political concept",
            "social issue",
            "social concept",
            "political ideology",
            "abstract concept",
            "business concept",
            "cultural practice",
            "legal term",
            "religion",
            "religious concept",
            "medical concept",
            "health condition",
            "symptom",
            "health concept",
            "scientific field",
            "financial term",
        ],
    ),
    ("AWARD", ["award", "academic degree"]),
    ("LAW / LEGAL / DOCUMENT", ["legal document", "document", "legislation", "law", "regulation", "policy"]),
    ("PROGRAM / PROJECT", ["program", "project", "government program", "educational program"]),
    ("SPORT", ["sport", "sports league", "game"]),
    (
        "INDUSTRY",
        [
            "industry",
            "economic sector",
            "business type",
            "financial instrument",
            "cryptocurrency",
            "financial product",
            "financial market",
            "economic indicator",
            "market",
        ],
    ),
    ("LANGUAGE", ["language", "pronoun"]),
    (
        "MATERIAL",
        [
            "material",
            "chemical compound",
            "substance",
            "ingredient",
            "chemical substance",
            "chemical element",
            "resource",
            "drug",
            "nutrient",
        ],
    ),
    (
        "BIOLOGY / NATURAL SCIENCE",
        [
            "body part",
            "medical procedure",
            "anatomical structure",
            "virus",
            "species",
            "plant",
            "biological entity",
            "fruit",
            "animal",
        ],
    ),
    ("DIGITAL / IDENTIFIER", ["phone number", "hashtag", "url"]),
    ("COLOR", ["color"]),
    ("ACTIVITY", ["activity"]),
    ("PROCESS", ["process"]),
    ("ACADEMIC DISCIPLINE", ["academic discipline"]),
    ("EDUCATIONAL LEVEL", ["educational level"]),
    ("ENTITY", ["entity"]),
    ("FIELD", ["field"]),
    ("FEATURE", ["feature"]),
    ("CATEGORY", ["category"]),
    ("CRIME", ["crime"]),
]


if __name__ == "__main__":
    base.main()
