/** Build readable classic-script bundles at the existing application URLs. */
import { build } from 'esbuild';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const entries = JSON.parse(await readFile(path.join(root, 'frontend/entries.json'), 'utf8'));
for (const [outfile, entryPoint] of Object.entries(entries)) {
  await build({
    absWorkingDir: root,
    entryPoints: [entryPoint],
    outfile,
    bundle: true,
    format: 'iife',
    platform: 'browser',
    external: ['/static/*'],
    target: ['es2022'],
    sourcemap: true,
    minify: false,
    legalComments: 'inline',
    banner: { js: '// Generated by npm run build; edit frontend/ sources.' }
  });
}
console.log(`Built ${Object.keys(entries).length} browser entrypoints.`);
