import { aliasesState } from './aliases.state.mjs';
export function initializeAliases() {
  aliasesState.LANGUAGE_ALIASES = {
    ar: 'arabic',
    arabic: 'arabic',
    fa: 'persian',
    persian: 'persian',
    farsi: 'persian',
    ur: 'urdu',
    urdu: 'urdu',
    hi: 'hindi',
    hindi: 'hindi',
    id: 'indonesian',
    indonesian: 'indonesian',
    'bahasa indonesia': 'indonesian',
    ta: 'tamil',
    tamil: 'tamil',
    th: 'thai',
    thai: 'thai',
    tr: 'turkish',
    turkish: 'turkish',
    ang: 'old-english',
    'old english': 'old-english',
    grc: 'ancient-greek',
    'ancient greek': 'ancient-greek',
    'classical greek': 'ancient-greek',
    he: 'hebrew',
    hebrew: 'hebrew',
    fr: 'french',
    french: 'french',
    it: 'italian',
    italian: 'italian',
    ru: 'russian',
    russian: 'russian',
    es: 'spanish',
    spanish: 'spanish',
    de: 'german',
    german: 'german',
    nl: 'dutch',
    dutch: 'dutch',
    pt: 'portuguese',
    portuguese: 'portuguese',
    la: 'latin',
    latin: 'latin',
    el: 'greek',
    greek: 'greek',
    'modern greek': 'greek',
    hy: 'armenian',
    armenian: 'armenian',
    tl: 'tagalog',
    tagalog: 'tagalog',
    sw: 'swahili',
    swahili: 'swahili',
    bn: 'bengali',
    bengali: 'bengali',
    pa: 'punjabi',
    punjabi: 'punjabi',
    gurmukhi: 'punjabi',
    ja: 'japanese',
    japanese: 'japanese',
    ko: 'korean',
    korean: 'korean',
    vi: 'vietnamese',
    vietnamese: 'vietnamese',
    zh: 'han',
    'zh-hant': 'han',
    lzh: 'han',
    'chinese (simplified)': 'han',
    'chinese simplified': 'han',
    'chinese (traditional)': 'han',
    'chinese traditional': 'han',
    'traditional-chinese': 'han',
    classical: 'han',
    'classical chinese': 'han',
    'classical-chinese': 'han'
  };
  return true;
}
