import { alphabetTablesState } from './alphabet-tables.state.mjs';
export function initializeAlphabetTables() {
  /* Greek */

  alphabetTablesState.GREEK_MARKS = {
    '\u0313': '',
    '\u0314': 'h',
    '\u0300': '',
    '\u0301': '',
    '\u0342': '',
    '\u0345': 'i'
  };
  alphabetTablesState.GREEK_ROUGH_BREATHING = new Set(['\u0314']);
  alphabetTablesState.GREEK_MODERN = {
    α: 'a',
    β: 'v',
    γ: 'g',
    δ: 'dh',
    ε: 'e',
    ζ: 'z',
    η: 'i',
    θ: 'th',
    ι: 'i',
    κ: 'k',
    λ: 'l',
    μ: 'm',
    ν: 'n',
    ξ: 'x',
    ο: 'o',
    π: 'p',
    ρ: 'r',
    σ: 's',
    ς: 's',
    τ: 't',
    υ: 'i',
    φ: 'f',
    χ: 'kh',
    ψ: 'ps',
    ω: 'o'
  };
  alphabetTablesState.GREEK_ANCIENT = {
    α: 'a',
    β: 'b',
    γ: 'g',
    δ: 'd',
    ε: 'e',
    ζ: 'zd',
    η: 'ē',
    θ: 'th',
    ι: 'i',
    κ: 'k',
    λ: 'l',
    μ: 'm',
    ν: 'n',
    ξ: 'ks',
    ο: 'o',
    π: 'p',
    ρ: 'r',
    σ: 's',
    ς: 's',
    τ: 't',
    υ: 'y',
    φ: 'ph',
    χ: 'kh',
    ψ: 'ps',
    ω: 'ō'
  };
  alphabetTablesState.GREEK_MODERN_SPAN = {
    αι: 'e',
    ει: 'i',
    οι: 'i',
    ου: 'u',
    αυ: 'av/af',
    ευ: 'ev/ef',
    ηυ: 'iv/if',
    γκ: 'gk',
    μπ: 'b',
    ντ: 'd',
    τσ: 'ts',
    τζ: 'dz'
  };
  alphabetTablesState.GREEK_ANCIENT_SPAN = {
    αι: 'ai',
    ει: 'ei',
    οι: 'oi',
    ου: 'ou',
    αυ: 'au',
    ευ: 'eu',
    ηυ: 'ēu',
    γγ: 'ng',
    γκ: 'nk',
    γχ: 'nkh'
  };

  /* Cyrillic / Armenian */

  alphabetTablesState.CYRILLIC_RUSSIAN = {
    а: 'a',
    б: 'b',
    в: 'v',
    г: 'g',
    д: 'd',
    е: 'e/ye',
    ё: 'yo',
    ж: 'zh',
    з: 'z',
    и: 'i',
    й: 'y',
    к: 'k',
    л: 'l',
    м: 'm',
    н: 'n',
    о: 'o',
    п: 'p',
    р: 'r',
    с: 's',
    т: 't',
    у: 'u',
    ф: 'f',
    х: 'kh',
    ц: 'ts',
    ч: 'ch',
    ш: 'sh',
    щ: 'shch',
    ъ: 'ʺ',
    ы: 'y',
    ь: 'ʹ',
    э: 'e',
    ю: 'yu',
    я: 'ya'
  };
  alphabetTablesState.ARMENIAN = {
    ա: 'a',
    բ: 'b',
    գ: 'g',
    դ: 'd',
    ե: 'e',
    զ: 'z',
    է: 'ē',
    ը: 'ə',
    թ: 'tʿ',
    ժ: 'zh',
    ի: 'i',
    լ: 'l',
    խ: 'kh',
    ծ: 'ts',
    կ: 'k',
    հ: 'h',
    ձ: 'dz',
    ղ: 'gh',
    ճ: 'č',
    մ: 'm',
    յ: 'y',
    ն: 'n',
    շ: 'sh',
    ո: 'o/vo',
    չ: 'chʿ',
    պ: 'p',
    ջ: 'j',
    ռ: 'ṙ',
    ս: 's',
    վ: 'v',
    տ: 't',
    ր: 'r',
    ց: 'cʿ',
    ւ: 'w',
    փ: 'pʿ',
    ք: 'kʿ',
    օ: 'ō',
    ֆ: 'f'
  };

  /* Japanese */
  return true;
}
